// ── Single source of truth for all tracked brands ──

export interface Brand {
  name: string;
  domain: string;
  products: string;
  lastUpdate: string;
  latestChange: string;
}

export interface Vertical {
  id: string;
  label: string;
  brands: Brand[];
}

// Helper to generate realistic-looking product counts and update times
function b(name: string, domain: string, products: string, lastUpdate: string, latestChange: string): Brand {
  return { name, domain, products, lastUpdate, latestChange };
}

export const VERTICALS: Vertical[] = [
  {
    id: "fashion",
    label: "Fashion",
    brands: [
      b("Gymshark", "gymshark.com", "2,847", "2h", "-12% on 4 items"),
      b("Fashion Nova", "fashionnova.com", "14,502", "1h", "38 new arrivals"),
      b("SKIMS", "skims.com", "1,923", "4h", "3 new products"),
      b("Alo Yoga", "aloyoga.com", "2,156", "2h", "14 new items"),
      b("Kith", "kith.com", "3,412", "3h", "New drop launched"),
      b("Steve Madden", "stevemadden.com", "3,671", "5h", "Seasonal sale -20%"),
      b("FIGS", "wearfigs.com", "867", "6h", "New colourway added"),
      b("Allbirds", "allbirds.com", "412", "8h", "Price increase +5%"),
      b("Bombas", "bombas.com", "1,234", "4h", "-6% on socks"),
      b("Taylor Stitch", "taylorstitch.com", "523", "6h", "Workshop sale"),
      b("OddBalls", "myoddballs.com", "345", "3h", "New prints added"),
      b("Tentree", "tentree.com", "678", "5h", "Earth collection drop"),
      b("Chubbies", "chubbies.com", "834", "7h", "Swim trunk restock"),
      b("Represent Clothing", "representclo.com", "1,123", "2h", "New season launch"),
      b("Outdoor Voices", "outdoorvoices.com", "456", "4h", "Colour refresh"),
      b("True Classic", "trueclassictees.com", "312", "3h", "Bundle pricing update"),
      b("Buck Mason", "buckmason.com", "267", "8h", "New denim line"),
      b("Vuori", "vuori.com", "1,567", "2h", "12 new styles"),
      b("Rhone", "rhone.com", "834", "5h", "Commuter collection"),
      b("Cuts Clothing", "cutsclothing.com", "189", "6h", "New crew neck"),
      b("MeUndies", "meundies.com", "567", "4h", "Print collaboration"),
      b("Stance", "stance.com", "2,345", "3h", "NBA collection update"),
      b("Happy Socks", "happysocks.com", "1,890", "5h", "Summer range"),
      b("Knix", "knix.com", "445", "7h", "Swim launch"),
      b("ThirdLove", "thirdlove.com", "312", "6h", "New fit finder"),
      b("Savage X Fenty", "savagex.com", "2,678", "1h", "Monthly drop"),
      b("Lunya", "lunya.co", "234", "8h", "Washable silk restock"),
      b("Rothy's", "rothys.com", "378", "4h", "New point colour"),
      b("Thursday Boots", "thursdayboots.com", "156", "1d", "Captain restock"),
      b("Greats", "greats.com", "89", "12h", "Royale new colour"),
      b("Vessi", "vessi.com", "123", "6h", "Waterproof Weekend"),
      b("MVMT", "mvmtwatches.com", "456", "5h", "New chronograph"),
      b("Daniel Wellington", "danielwellington.com", "678", "4h", "Icon collection"),
      b("Away", "awaytravel.com", "234", "8h", "Aluminium restock"),
      b("Monos", "monos.com", "167", "7h", "New Metro colour"),
      b("Bellroy", "bellroy.com", "312", "5h", "Transit collection"),
      b("Ridge Wallet", "ridgewallet.com", "234", "4h", "New titanium finish"),
      b("Ekster", "ekster.com", "145", "6h", "Parliament wallet update"),
      // ── New fashion brands ──
      b("Todd Snyder", "toddsnyder.com", "1,456", "3h", "Italian leather collection"),
      b("Marine Layer", "marinelayer.com", "734", "5h", "Re-Spun tees restock"),
      b("Public Rec", "publicrec.com", "145", "8h", "All Day Every Day new colour"),
      b("Western Rise", "westernrise.com", "87", "1d", "Diversion pant update"),
      b("Mack Weldon", "mackweldon.com", "423", "3h", "Silver underwear restock"),
      b("OBEY Clothing", "obeyclothing.com", "1,867", "2h", "Summer graphic tees"),
      b("The Hundreds", "thehundreds.com", "2,134", "4h", "Adam Bomb collab drop"),
      b("Only NY", "onlyny.com", "312", "6h", "Fishing hat restock"),
      b("Koio", "koio.co", "78", "12h", "Capri triple white launch"),
      b("Oliver Cabell", "olivercabell.com", "134", "5h", "Low 1 new colourway"),
      b("Quay Australia", "quayaustralia.com", "567", "2h", "-15% on polarized styles"),
      b("Vincero", "vincerowatches.com", "189", "7h", "Chrono S new dial"),
    ],
  },
  {
    id: "beauty",
    label: "Beauty & Wellness",
    brands: [
      b("Fenty Beauty", "fentybeauty.com", "1,241", "1h", "New collection launched"),
      b("Rare Beauty", "rarebeauty.com", "534", "3h", "5 new shades"),
      b("Kylie Cosmetics", "kyliecosmetics.com", "687", "4h", "Lip kit restocked"),
      b("Glossier", "glossier.com", "312", "8h", "-8% on skincare"),
      b("ColourPop", "colourpop.com", "3,891", "2h", "Disney collab drop"),
      b("Hismile", "hismile.com", "156", "6h", "New flavour added"),
      b("Olaplex", "olaplex.com", "89", "1d", "Bundle pricing updated"),
      b("Tropic Skincare", "tropicskincare.com", "234", "5h", "3 products restocked"),
      b("The Beauty Chef", "thebeautychef.com", "67", "12h", "New supplement line"),
      b("Summer Fridays", "summerfridays.com", "98", "7h", "Limited edition SPF"),
      b("Jeffree Star Cosmetics", "jeffreestarcosmetics.com", "567", "3h", "Mystery box sale"),
      b("Iconic London", "iconiclondoninc.com", "234", "5h", "Illuminator restock"),
      b("Kosas Cosmetics", "kfrancis.kosas.com", "145", "6h", "Tinted oil update"),
      b("Glow Recipe", "glowrecipe.com", "178", "4h", "Watermelon set"),
      b("Dr. Squatch", "drsquatch.com", "312", "2h", "New bar scents"),
      b("Harry's", "harrys.com", "189", "5h", "Shave set refresh"),
      b("Ouai", "theouai.com", "156", "7h", "New treatment mask"),
      b("Function of Beauty", "functionofbeauty.com", "78", "8h", "Body line expansion"),
      b("Ritual", "ritual.com", "45", "6h", "Protein powder launch"),
      b("Athletic Greens", "drinkag1.com", "34", "1d", "Travel pack update"),
      b("Mud/Wtr", "mudwtr.com", "56", "8h", ":rest blend restock"),
      b("Vital Proteins", "vitalproteins.com", "234", "4h", "Collagen bars"),
      b("Quip", "getquip.com", "89", "1d", "Smart brush update"),
      b("Snow Teeth Whitening", "trysnow.com", "67", "6h", "LED kit refresh"),
      b("Blueland", "blueland.com", "78", "5h", "Laundry tablets"),
      // ── New beauty brands ──
      b("Cocokind", "cocokind.com", "112", "3h", "Ceramide barrier serum launch"),
      b("Pixi Beauty", "pixibeauty.com", "456", "2h", "Glow Tonic bundle update"),
      b("Stila Cosmetics", "stilacosmetics.com", "389", "5h", "Glitter & Glow restock"),
      b("Beauty Bakerie", "beautybakerie.com", "234", "4h", "Flour Setting Powder new shade"),
      b("Josie Maran", "josiemaran.com", "178", "6h", "Argan oil holiday set"),
      b("The Honey Pot", "thehoneypot.co", "145", "3h", "New herbal wash"),
      b("Lumin", "luminskin.com", "67", "8h", "Dark circle defense restock"),
      b("Geologie", "geologie.com", "34", "1d", "Personalized routine refresh"),
      b("Tiege Hanley", "tifriegehanley.com", "56", "5h", "Level 2 system update"),
      b("Oars + Alps", "oarsandalps.com", "89", "7h", "Aluminum-free deodorant restock"),
      b("Native", "nativecos.com", "234", "2h", "-20% on body wash"),
      b("Kopari", "koparibeauty.com", "167", "4h", "Coconut deodorant new scent"),
      b("Prose", "prose.com", "45", "12h", "Custom haircare formula update"),
      b("Hims & Hers", "forhims.com", "312", "1h", "New skincare line launched"),
      b("Moon Juice", "moonjuice.com", "89", "6h", "SuperYou restock"),
      b("Golde", "golde.co", "56", "8h", "Matcha turmeric latte new flavour"),
      b("Hum Nutrition", "humnutrition.com", "78", "5h", "Gummy vitamin expansion"),
      b("Olly", "olly.com", "145", "3h", "Sleep gummy restock"),
      b("Pura", "pura.com", "234", "2h", "New fragrance collaboration"),
      b("Vitruvi", "vitruvi.com", "67", "7h", "Stone diffuser new colour"),
      b("Saje Natural Wellness", "saje.com", "312", "4h", "Essential oil blend launch"),
      b("Grove Collaborative", "grove.co", "1,567", "1h", "Spring cleaning bundle"),
      b("Tru Earth", "tru.earth", "34", "1d", "Laundry strips new scent"),
      b("Lume", "lumedeodorant.com", "123", "3h", "Whole body deodorant restock"),
      b("Burst Oral Care", "bfrst.com", "45", "8h", "Sonic brush head refill"),
    ],
  },
  {
    id: "home",
    label: "Home & Garden",
    brands: [
      b("Ruggable", "ruggable.com", "4,123", "1h", "48 new designs"),
      b("Casper", "casper.com", "234", "3h", "Mattress sale -15%"),
      b("Arhaus", "arhaus.com", "5,671", "2h", "New outdoor collection"),
      b("Stanley 1913", "stanley1913.com", "567", "4h", "New tumbler colour"),
      b("Brooklinen", "brooklinen.com", "456", "6h", "Seasonal bundle update"),
      b("Parachute Home", "parachutehome.com", "389", "5h", "Price drop on linens"),
      b("Boll & Branch", "bollandbranch.com", "312", "8h", "New thread count line"),
      b("Fast Growing Trees", "fastgrowingtrees.com", "1,456", "3h", "Spring stock update"),
      b("Leesa", "leesa.com", "123", "1d", "Hybrid mattress refresh"),
      b("Burrow", "burrow.com", "345", "4h", "Nomad sofa new colour"),
      b("Article", "article.com", "2,345", "2h", "Mid-century restock"),
      b("Outer", "liveouter.com", "89", "8h", "Outdoor sofa update"),
      b("Yeti", "yeti.com", "678", "3h", "New Rambler colour"),
      b("Hydro Flask", "hydroflask.com", "456", "5h", "Wide Mouth restock"),
      b("Solo Stove", "solostove.com", "123", "6h", "Mesa tabletop fire pit"),
      b("Ooni", "ooni.com", "89", "7h", "Koda 2 Max launch"),
      b("Rumpl", "rumpl.com", "234", "4h", "National Parks series"),
      b("Peak Design", "peakdesign.com", "312", "5h", "Travel Backpack V2"),
      b("Nomatic", "nomatic.com", "178", "6h", "Navigator expansion"),
      b("Elgato", "elgato.com", "145", "4h", "Stream Deck Neo"),
      b("Keychron", "keychron.com", "234", "3h", "Q series restock"),
      b("Secretlab", "secretlab.co", "156", "6h", "TITAN Evo new fabric"),
      // ── New home brands ──
      b("Purple", "purple.com", "267", "2h", "Hybrid Premier mattress restock"),
      b("Joybird", "joybird.com", "1,234", "3h", "Sectional new fabric options"),
      b("Floyd", "floydhome.com", "89", "8h", "The Bed frame walnut restock"),
      b("Interior Define", "interiordefine.com", "567", "5h", "Custom sofa lead time update"),
      b("Neighbor", "neighbor.com", "45", "1d", "Performance mattress price drop -10%"),
      b("RTIC", "rticoutdoors.com", "456", "2h", "Tumbler new colours"),
      b("Corkcicle", "corkcicle.com", "345", "4h", "Canteen restock"),
      b("Larq", "lfrqcom.myshopify.com", "67", "7h", "Self-cleaning bottle V2"),
      b("S'well", "swell.com", "289", "3h", "Traveler collection launch"),
      b("Traeger", "traeger.com", "312", "5h", "Ironwood pellet grill update"),
      b("Breeo", "breeo.co", "78", "8h", "X Series fire pit restock"),
      b("Gozney", "gozney.com", "56", "6h", "Dome S1 pizza oven launch"),
      b("BioLite", "bfrioliteenergy.com", "145", "4h", "CampStove 2 bundle"),
      b("Snow Peak", "snowpeak.com", "567", "3h", "Titanium cookware restock"),
      b("Big Agnes", "bigagnes.com", "423", "5h", "Copper Spur tent update"),
      b("Sea to Summit", "seatosummit.com", "678", "2h", "Sleeping pad new model"),
      b("Aer", "aersf.com", "123", "7h", "Travel Pack 3 restock"),
      b("Timbuk2", "timbuk2.com", "456", "3h", "Classic Messenger refresh"),
      b("Chrome Industries", "chromeindustries.com", "345", "5h", "Citizen new colourway"),
      b("Society6", "society6.com", "12,456", "1h", "8,400 new artist prints"),
      b("Sandmarc", "sandmarc.com", "89", "8h", "iPhone lens kit update"),
      b("Polaroid", "polaroid.com", "178", "4h", "Go Generation 2 camera launch"),
      b("Weber", "weber.com", "345", "6h", "Spirit series price drop -12%"),
      b("Maiden Home", "maidenhome.com", "67", "1d", "Sullivan sofa new fabric"),
      b("Incase", "incase.com", "234", "5h", "Icon Backpack restock"),
      b("Tortuga", "tortugabackpacks.com", "45", "12h", "Outbreaker 45L update"),
      b("Waterfield Designs", "sfbags.com", "156", "3h", "Air Porter carry-on launch"),
      b("Minaal", "minaal.com", "34", "2d", "Carry-on 3.0 restock"),
    ],
  },
  {
    id: "food",
    label: "Food & Beverage",
    brands: [
      b("Liquid Death", "liquiddeath.com", "156", "5h", "New flavour launched"),
      b("Huel", "huel.com", "178", "4h", "Price drop -10%"),
      b("Magic Spoon", "magicspoon.com", "42", "1d", "New cereal bars"),
      b("Death Wish Coffee", "deathwishcoffee.com", "89", "8h", "Reserve blend added"),
      b("Red Bull Shop", "redbullshopus.com", "312", "6h", "New merch collection"),
      b("Fly by Jing", "flybyjing.com", "67", "3h", "Gift set updated"),
      b("Owala", "owala.com", "145", "2h", "FreeSip new colours"),
      b("Stumptown Coffee", "stumptowncoffee.com", "78", "7h", "Subscription pricing change"),
      b("Partake Foods", "partakefoods.com", "34", "1d", "New cookie flavour"),
      b("Heatonist", "heatonist.com", "256", "4h", "Hot Ones bundle"),
      b("Milk Bar", "milkbarstore.com", "123", "3h", "Birthday cake restock"),
      b("Chomps", "chomps.com", "67", "6h", "New original flavour"),
      b("Soylent", "soylent.com", "45", "8h", "Complete Protein update"),
      b("Daily Harvest", "daily-harvest.com", "312", "2h", "Summer smoothies"),
      b("Our Place", "fromourplace.com", "89", "5h", "Always Pan 2.0 Sage"),
      b("Caraway", "carawayhome.com", "134", "6h", "Bakeware Set Navy"),
      b("Made In Cookware", "madeincookware.com", "234", "4h", "Carbon steel restock"),
      b("HexClad", "hexclad.com", "89", "7h", "Gordon Ramsay set"),
      b("Fellow", "fellowproducts.com", "156", "3h", "Stagg EKG update"),
      b("Aeropress", "aeropress.com", "34", "1d", "Clear model launch"),
      b("Chemex", "chemexcoffeemaker.com", "23", "2d", "Glass handle restock"),
      // ── New food brands ──
      b("Chamberlain Coffee", "chamberlaincoffee.com", "78", "3h", "New matcha blend launch"),
      b("Levain Bakery", "levainbakery.com", "45", "5h", "Seasonal cookie box"),
      b("Splendid Spoon", "splendidspoon.com", "89", "4h", "Smoothie bowl new flavours"),
      b("Sakara Life", "sakara.com", "134", "2h", "Meal delivery menu refresh"),
      b("ButcherBox", "butcherbox.com", "67", "8h", "Grass-fed beef bundle update"),
      b("Crowd Cow", "crowdcow.com", "345", "3h", "Wagyu restock"),
      b("Snake River Farms", "snakeriverfarms.com", "156", "6h", "American Wagyu brisket restock"),
      b("Thrive Market", "thrivemarket.com", "4,567", "1h", "2,300 products price updated"),
      b("Misfits Market", "misfitsmarket.com", "1,234", "2h", "Organic produce box refresh"),
      b("Great Jones", "greatjonesgoods.com", "45", "1d", "Dutchess new colour"),
      b("Misen", "misen.com", "89", "5h", "Chef's knife restock"),
      b("Material Kitchen", "materialkitchen.com", "67", "7h", "reBoard cutting board launch"),
      b("Baratza", "baratza.com", "34", "12h", "Encore ESP grinder launch"),
      b("Flair Espresso", "flairespresso.com", "23", "8h", "Pro 2 new colour"),
      b("Hario", "hfrario-usa.com", "145", "4h", "V60 drip kettle restock"),
      b("Timemore", "timemore.com", "78", "6h", "C3 grinder new colour"),
      b("Graza", "grfraza.co", "34", "3h", "Sizzle olive oil restock"),
      b("Ghia", "drinkghia.com", "23", "5h", "Non-alcoholic aperitivo bundle"),
      b("Olipop", "drinkolipop.com", "56", "2h", "New cherry cola flavour"),
      b("Poppi", "drinkpoppi.com", "45", "4h", "Strawberry lemon restock"),
      b("Beekeeper's Naturals", "beekeepersnaturals.com", "78", "7h", "Propolis throat spray bundle"),
      b("MUDWTR", "mudwtr.com", "56", "8h", ":energy blend launch"),
      b("Four Sigmatic", "foursigmatic.com", "123", "3h", "Mushroom coffee restock"),
      b("Laird Superfood", "lairdsuperfood.com", "89", "6h", "Creamer new flavour"),
      b("Trade Coffee", "dfrrinktrade.com", "567", "1h", "New roaster partner added"),
      b("Verve Coffee", "vervecoffee.com", "67", "5h", "Streetlevel blend restock"),
      b("Intelligentsia", "intelligentsia.com", "89", "4h", "Black Cat espresso update"),
      b("Counter Culture", "counterculturecoffee.com", "45", "8h", "Hologram decaf restock"),
      b("Blue Bottle Coffee", "bluebottlecoffee.com", "78", "3h", "Subscription gift set launch"),
    ],
  },
  {
    id: "electronics",
    label: "Electronics & Tech",
    brands: [
      b("Nomad Goods", "nomadgoods.com", "189", "3h", "iPhone 16 cases"),
      b("Ridge Wallet", "ridgewallet.com", "234", "4h", "New titanium finish"),
      b("Cowboy", "cowboy.com", "23", "1d", "E-bike price update"),
      b("Secretlab", "secretlab.co", "156", "6h", "New TITAN Evo"),
      b("Pela Case", "pelacase.com", "312", "5h", "Compostable range expanded"),
      b("Master & Dynamic", "masterdynamic.com", "89", "8h", "New wireless model"),
      b("Jackery", "jackery.com", "78", "3h", "Solar panel bundle"),
      b("Moment", "shopmoment.com", "678", "4h", "CineBloom restock"),
      b("Nanoleaf", "nanoleaf.me", "45", "7h", "Skylight panel launch"),
      b("Elgato", "elgato.com", "145", "4h", "Stream Deck update"),
      b("Loop Earplugs", "loopearplugs.com", "67", "6h", "Switch new colour"),
      b("MVMT Watches", "mvmtwatches.com", "456", "5h", "Arc Automatic"),
      b("Keychron", "keychron.com", "234", "3h", "Q1 Max restock"),
      b("Shokz", "shokz.com", "78", "8h", "OpenRun Pro 2"),
      b("RhinoShield", "rhinoshield.io", "567", "2h", "SolidSuit new designs"),
      b("Framework Laptop", "frame.work", "23", "1d", "16\" expansion cards"),
      b("Razer", "razer.com", "1,234", "1h", "Viper V3 launch"),
      b("Logitech G", "logitechg.com", "567", "3h", "Pro X Superlight 2"),
      b("Raspberry Pi", "raspberrypi.com", "89", "6h", "Pi 5 restock"),
      // ── New electronics brands ──
      b("Sennheiser", "sennheiser.com", "456", "2h", "Momentum 4 new colour"),
      b("Paperlike", "paperlike.com", "34", "8h", "iPad Pro screen protector V2"),
      b("SteelSeries", "steelseries.com", "345", "3h", "Arctis Nova Pro restock"),
      b("Corsair", "corsair.com", "1,567", "1h", "K100 RGB keyboard update"),
      b("NZXT", "nzxt.com", "234", "4h", "H7 Flow case new colour"),
      b("Fractal Design", "fractal-design.com", "145", "5h", "North case restock"),
      b("Glorious Gaming", "gloriousgaming.com", "312", "3h", "GMMK 3 launch"),
      b("Ducky", "dfruckychannel.com", "178", "6h", "One 3 new switches"),
      b("Arduino", "store.arduino.cc", "89", "7h", "UNO R4 WiFi restock"),
      b("System76", "system76.com", "34", "1d", "Pangolin laptop refresh"),
      b("Purism", "puri.sm", "23", "2d", "Librem 14 V2 update"),
      b("Pine64", "pine64.org", "45", "12h", "PinePhone Pro restock"),
      b("Native Union", "nativeunion.com", "156", "4h", "Dock wireless charger update"),
      b("Anker", "anker.com", "2,345", "1h", "Prime Day bundle pricing"),
      b("Twelve South", "twelvesouth.com", "89", "5h", "BookArc new finish"),
      b("CalDigit", "caldigit.com", "45", "8h", "TS4 Thunderbolt dock restock"),
      b("Dbrand", "dbrand.com", "4,567", "2h", "Teardown skin new devices"),
      b("Analogue", "analogue.co", "23", "2d", "Pocket limited edition"),
      b("Teenage Engineering", "teenage.engineering", "67", "3h", "EP-133 restock"),
      b("Nothing", "nothing.tech", "34", "5h", "Ear (a) new colour"),
      b("Remarkable", "remarkable.com", "23", "1d", "Paper Pro accessories launch"),
      b("Supernote", "supernote.com", "34", "8h", "Nomad case update"),
      b("Boox", "shop.boox.com", "78", "4h", "Tab Ultra C Pro launch"),
      b("Oura", "ouraring.com", "45", "6h", "Ring Gen 4 new finish"),
      b("Whoop", "whoop.com", "34", "7h", "4.0 band new colours"),
      b("Bambu Lab", "bambulab.com", "56", "3h", "A1 Mini bundle restock"),
      b("Prusa", "prusa3d.com", "89", "5h", "MK4S upgrade kit launch"),
      b("Creality", "store.creality.com", "234", "2h", "K1 Max new firmware bundle"),
      b("Elegoo", "elegoo.com", "178", "4h", "Saturn 4 Ultra launch"),
      b("Lume Pad", "lfreiagear.com", "23", "1d", "Lume Pad 2 price drop -15%"),
      b("Insta360", "store.insta360.com", "67", "3h", "X4 action cam bundle"),
    ],
  },
  {
    id: "sports",
    label: "Sports & Outdoors",
    brands: [
      b("HOKA", "hoka.com", "1,234", "2h", "Clifton 9 new colourway"),
      b("Tracksmith", "tracksmith.com", "312", "4h", "NDO collection restock"),
      b("Cotopaxi", "cotopaxi.com", "867", "3h", "Del Dia pack new colours"),
      b("G/FORE", "gfore.com", "534", "5h", "Gallivanter shoe launch"),
      b("Gymshark", "gymshark.com", "2,847", "2h", "Vital seamless restock"),
      b("On Running", "on.com", "1,456", "1h", "Cloudmonster 2 launch"),
      b("Brooks Running", "brooksrunning.com", "1,678", "3h", "Ghost 16 new colour"),
      b("Salomon", "salomon.com", "2,345", "2h", "XT-6 restock all sizes"),
      b("Arc'teryx", "arcteryx.com", "1,890", "4h", "Beta LT Gore-Tex restock"),
      b("Patagonia", "patagonia.com", "3,456", "1h", "Nano Puff new colourways"),
      b("The North Face", "thenorthface.com", "4,567", "2h", "Nuptse jacket restock"),
      b("REI Co-op", "rei.com", "15,234", "1h", "Anniversary sale launched"),
      b("Backcountry", "backcountry.com", "12,456", "1h", "Semi-annual sale -25%"),
      b("Moosejaw", "moosejaw.com", "6,789", "3h", "Clearance section updated"),
      b("Rab", "rab.equipment", "678", "6h", "Microlight Alpine restock"),
      b("Mountain Hardwear", "mountainhardwear.com", "1,234", "5h", "Ghost Whisperer update"),
      b("Black Diamond", "blackdiamondequipment.com", "1,567", "4h", "Spot 400 headlamp launch"),
      b("Petzl", "petzl.com", "456", "7h", "Actik Core restock"),
      b("Osprey", "osprey.com", "534", "3h", "Atmos AG 65 new colour"),
      b("Gregory", "gregorypacks.com", "423", "5h", "Baltoro refresh"),
      b("Deuter", "deuter.com", "567", "6h", "Aircontact Lite update"),
      b("MSR", "msrgear.com", "312", "8h", "PocketRocket Deluxe restock"),
      b("Jetboil", "jetboil.com", "89", "1d", "Flash cooking system bundle"),
      b("GSI Outdoors", "gsioutdoors.com", "234", "7h", "Pinnacle cookset restock"),
      b("Camp Chef", "campchef.com", "345", "4h", "Woodwind pellet grill update"),
      b("ENO", "eaglesnestoutfittersinc.com", "178", "5h", "DoubleNest hammock new print"),
      b("Kammok", "kammok.com", "123", "6h", "Roo Double hammock restock"),
      b("Topo Designs", "topodesigns.com", "456", "3h", "Rover Pack Classic new colour"),
      b("Mystery Ranch", "mysteryranch.com", "678", "4h", "ASAP pack restock"),
      b("Kifaru", "kifaru.net", "234", "1d", "Reckoning frame update"),
      b("Stone Glacier", "stoneglacier.com", "156", "8h", "Sky 5900 pack launch"),
      b("First Lite", "firstlite.com", "345", "5h", "Obsidian merino base layer"),
      b("Sitka Gear", "sitkagear.com", "567", "3h", "Optifade Subalpine restock"),
      b("Kuiu", "kuiu.com", "423", "6h", "Attack pant new colour"),
      b("Simms Fishing", "simmsfishing.com", "789", "4h", "G3 waders restock"),
      b("Orvis", "orvis.com", "3,456", "2h", "Clearwater fly rod update"),
      b("Filson", "filson.com", "1,234", "5h", "Mackinaw Cruiser restock"),
      b("Duluth Trading", "duluthtrading.com", "8,567", "1h", "Fire Hose pants sale -15%"),
      b("Carhartt WIP", "carhartt-wip.com", "1,678", "3h", "Michigan coat restock"),
      b("5.11 Tactical", "511tactical.com", "3,456", "2h", "Rush backpack update"),
      b("Vertx", "vertx.com", "567", "6h", "Gamut 2.0 pack restock"),
      b("Viktos", "viktos.com", "345", "7h", "Operatus glove new colour"),
      b("Under Armour", "underarmour.com", "9,876", "1h", "Curry 11 launch"),
      b("New Balance", "newbalance.com", "5,678", "1h", "990v6 restock all sizes"),
      b("Puma", "puma.com", "7,456", "2h", "Suede XL new colourways"),
      b("Fabletics", "fabletics.com", "2,345", "3h", "New member deal update"),
      b("Sweaty Betty", "sweatybetty.com", "1,567", "4h", "Power legging new prints"),
      b("Lululemon", "lululemon.com", "4,567", "1h", "Align pant restock"),
      b("Athleta", "athleta.com", "3,234", "2h", "Rainier tight new colour"),
      b("Vuori", "vuori.com", "1,567", "3h", "Kore Short new colour"),
    ],
  },
  {
    id: "kids",
    label: "Kids & Baby",
    brands: [
      b("Lovevery", "lovevery.com", "89", "6h", "New play kit stage launch"),
      b("Primary", "primary.com", "456", "3h", "Rainbow collection restock"),
      b("Little Sleepies", "littlesleepies.com", "567", "2h", "Bamboo PJs new print"),
      b("Nugget", "nuggetcomfort.com", "34", "8h", "Limited edition colour drop"),
      b("KiwiCo", "kiwico.com", "234", "4h", "Tinker Crate summer box"),
      b("Owlet", "owletcare.com", "45", "7h", "Dream Sock V3 restock"),
      b("Lalo", "meetlalo.com", "78", "5h", "The Chair new colour"),
      b("Aden + Anais", "adenandanais.com", "345", "3h", "Muslin swaddle new prints"),
      b("Monica + Andy", "monicaandandy.com", "234", "4h", "Organic layette restock"),
      b("Maisonette", "maisonette.com", "4,567", "1h", "Spring designer edit"),
      b("Hanna Andersson", "hannaandersson.com", "1,234", "2h", "Organic PJs new prints"),
      b("Tea Collection", "teacollection.com", "789", "3h", "Global prints new season"),
      b("Cat & Jack", "catandjack.com", "2,345", "2h", "Summer basics launch"),
      b("Boden Mini", "bodenusa.com", "1,567", "4h", "Fun prints restock"),
      b("Petit Bateau", "petit-bateau.us", "678", "5h", "Mariniere tee new colours"),
      b("Rylee + Cru", "ryleeandcru.com", "312", "6h", "Spring collection drop"),
      b("Jamie Kay", "jamiekay.com", "423", "5h", "Organic cotton essentials"),
      b("Quincy Mae", "quincymae.com", "267", "4h", "Ribbed knotted gown restock"),
      b("Kyte Baby", "kytebaby.com", "534", "2h", "Bamboo sleep bag new colour"),
      b("Little Unicorn", "littleunicorn.com", "189", "6h", "Cotton muslin quilt restock"),
      b("Copper Pearl", "copperpearl.com", "312", "3h", "Knit blanket new patterns"),
      b("Mushie", "mushie.com", "234", "4h", "Silicone plate set new colour"),
      b("Pehr", "pfrehrdesigns.com", "178", "5h", "Nursery mobile restock"),
      b("Gathre", "gathre.com", "123", "7h", "Leather mat new colour"),
      b("Stokke", "stokke.com", "145", "6h", "Tripp Trapp new finish"),
      b("UPPAbaby", "uppababy.com", "89", "8h", "Vista V3 new colour"),
      b("Bugaboo", "bugaboo.com", "67", "7h", "Fox 5 accessory bundle"),
      b("Nuna", "nunababy.com", "78", "5h", "RAVA car seat new colour"),
      b("Cybex", "cybex-online.com", "123", "6h", "Sirona S update"),
      b("Doona", "doona.com", "34", "1d", "Liki trike new colour"),
      b("BabyBjorn", "babybjorn.com", "89", "8h", "Bouncer Bliss restock"),
      b("Ergobaby", "ergobaby.com", "145", "4h", "Omni Breeze new colour"),
      b("Tula", "babytula.com", "178", "5h", "Explore carrier restock"),
      b("Boba", "boba.com", "67", "7h", "Boba X new print"),
      b("LILLEbaby", "lillebaby.com", "89", "6h", "Complete All Seasons restock"),
      b("Baby Brezza", "babybrezza.com", "56", "8h", "Formula Pro Advanced restock"),
      b("Elvie", "elvie.com", "34", "1d", "Stride pump launch"),
      b("Willow", "onewillow.com", "23", "12h", "Willow Go bundle update"),
      b("Haakaa", "haakaa.com", "145", "3h", "Gen 3 pump new colour"),
      b("Boppy", "boppy.com", "78", "5h", "Original pillow new cover"),
      b("DockATot", "dockatot.com", "67", "6h", "Deluxe+ new print"),
      b("Snoo", "happiestbaby.com", "23", "2d", "Snoo rental program update"),
      b("Nanit", "nanit.com", "45", "7h", "Pro camera bundle restock"),
      b("Hatch", "hatchwfraby.com", "34", "8h", "Rest+ 2nd Gen launch"),
      b("Tubby Todd", "tubbytodd.com", "89", "4h", "All Over Ointment restock"),
      b("Mustela", "mustelausa.com", "156", "3h", "Newborn set updated"),
      b("Pipette", "pipfrette.com", "78", "5h", "Baby balm restock"),
      b("Babyganics", "babyganics.com", "123", "4h", "Sunscreen SPF 50 restock"),
      b("Earth Mama", "earthmamaorganics.com", "145", "6h", "Nipple butter restock"),
      b("Honest Company", "honest.com", "567", "2h", "Diaper bundle new prints"),
    ],
  },
  {
    id: "pets",
    label: "Pets",
    brands: [
      b("BarkBox", "barkbox.com", "345", "2h", "Super Chewer box update"),
      b("Wild One", "wildone.com", "89", "5h", "Harness Walk Kit new colour"),
      b("Fi", "tryfi.com", "34", "7h", "Series 3 collar restock"),
      b("Ollie", "myollie.com", "45", "6h", "Fresh recipe rotation update"),
      b("The Farmer's Dog", "thefarmersdog.com", "56", "4h", "Beef recipe reformulated"),
      b("Sundays for Dogs", "sundaysfordogs.com", "23", "8h", "Air-dried food new protein"),
      b("Open Farm", "openfarmpet.com", "234", "3h", "RawMix kibble restock"),
      b("Stella & Chewy's", "stellaandchewys.com", "567", "2h", "Freeze-dried dinner restock"),
      b("Orijen", "orijenpetfoods.com", "123", "5h", "Regional Red reformulated"),
      b("Acana", "acana.com", "145", "6h", "Grasslands new bag size"),
      b("Ziwi Peak", "ziwipets.com", "178", "4h", "Venison recipe restock"),
      b("Nom Nom", "nomnomnow.com", "34", "7h", "Meal plan pricing update"),
      b("JustFoodForDogs", "justfoodfordogs.com", "89", "5h", "Pantry Fresh new recipe"),
      b("PetPlate", "petplate.com", "45", "6h", "Barkin' Beef restock"),
      b("Spot & Tango", "spotandtango.com", "56", "8h", "UnKibble new flavour"),
      b("A Pup Above", "apupabove.com", "34", "1d", "Porky's Luau restock"),
      b("Jinx", "thinkjinx.com", "67", "4h", "Salmon kibble launch"),
      b("Portland Pet Food", "portlandpetfood.com", "45", "7h", "Homestyle meal restock"),
      b("Chippin", "chippin.com", "23", "8h", "Cricket protein treat restock"),
      b("Yummers", "yummers.com", "34", "5h", "Functional mix-in new flavour"),
      b("Kong", "kongcompany.com", "456", "3h", "Classic Kong restock all sizes"),
      b("West Paw", "westpaw.com", "234", "4h", "Zogoflex Qwizl restock"),
      b("P.L.A.Y.", "petplay.com", "312", "5h", "Pet bed new print collection"),
      b("Ruffwear", "ruffwear.com", "267", "3h", "Front Range harness new colour"),
      b("Kurgo", "kurgo.com", "178", "6h", "Tru-Fit harness restock"),
      b("Sleepypod", "sleepypod.com", "45", "1d", "Clickit Sport new colour"),
      b("Fable Pets", "ffrablefrpets.com", "34", "7h", "The Game toy restock"),
      b("Maxbone", "maxbone.com", "89", "5h", "Jumbo Triangle toy launch"),
      b("Found My Animal", "foundmyanimal.com", "123", "4h", "Adjustable rope leash restock"),
      b("Zee.Dog", "zeedog.com", "345", "3h", "Gotham harness new prints"),
      b("Wolfgang Man & Beast", "wolfgangusa.com", "178", "6h", "DarkFloral collar restock"),
      b("Wildebeest", "wildebeest.co", "67", "8h", "Funston harness new colour"),
      b("Up Country", "upcountryinc.com", "456", "4h", "Spring pattern collection"),
      b("The Foggy Dog", "thefoggydog.com", "234", "5h", "Bandana new prints"),
      b("Harry Barker", "harrybarker.com", "189", "6h", "Eco-friendly bed restock"),
      b("Rifle Paper Co Pets", "riflepaperco.com", "67", "7h", "Garden Party collar launch"),
      b("Waggo", "waggo.com", "45", "8h", "Ceramic bowl new colours"),
      b("Diggs", "diggs.pet", "34", "5h", "Revol crate new colour"),
      b("Gunner Kennels", "gfrunnerkennels.com", "23", "1d", "G1 kennel Intermediate restock"),
      b("Impact Dog Crates", "impactdogcrates.com", "34", "12h", "Collapsible crate restock"),
      b("Ruffland", "rfrufflandkennels.com", "23", "2d", "Performance kennel update"),
      b("Dakota 283", "dakota283.com", "45", "8h", "G3 kennel new colour"),
      b("Whistle", "whistle.com", "34", "6h", "Health + GPS bundle update"),
      b("FitBark", "fitbark.com", "23", "7h", "FitBark 2 new colour"),
      b("Tractive", "tractive.com", "45", "4h", "GPS tracker new model"),
      b("PitPat", "pitpat.com", "23", "8h", "GPS tracker restock"),
      b("Catit", "catit.com", "312", "3h", "Flower fountain restock"),
      b("Litter-Robot", "litter-robot.com", "56", "5h", "LR4 bundle pricing update"),
      b("Tuft + Paw", "tuftandpaw.com", "89", "4h", "Cove litter box new colour"),
      b("Fable", "ffrablefrpets.com", "45", "6h", "The Crate mat restock"),
    ],
  },
  {
    id: "fitness",
    label: "Health & Fitness",
    brands: [
      b("Therabody", "therabody.com", "178", "3h", "Theragun PRO Plus launch"),
      b("Whoop", "whoop.com", "34", "5h", "4.0 strap new colours"),
      b("Oura", "ouraring.com", "45", "6h", "Gen 4 Horizon new finish"),
      b("Tonal", "tonal.com", "23", "1d", "Accessory bundle update"),
      b("Peloton", "apparel.onepeloton.com", "312", "4h", "Summer merch collection"),
      b("Hyperice", "hyperice.com", "89", "5h", "Hypervolt 2 Pro restock"),
      b("NormaTec", "hyperice.com/normatec", "34", "7h", "3 legs system restock"),
      b("Rogue Fitness", "roguefrfitness.com", "5,678", "1h", "Ohio Bar restock"),
      b("Rep Fitness", "repfitness.com", "1,234", "2h", "FB-5000 bench restock"),
      b("Titan Fitness", "titanfitness.com", "2,345", "1h", "T-3 rack sale -10%"),
      b("PRx Performance", "prxperformance.com", "345", "5h", "Profile rack restock"),
      b("Fringe Sport", "fringesport.com", "678", "3h", "Bumper plates restock"),
      b("Bells of Steel", "bellsofsteel.com", "456", "4h", "Adjustable bench update"),
      b("Eleiko", "eleiko.com", "234", "6h", "IWF competition set restock"),
      b("Concept2", "concept2.com", "45", "1d", "RowErg restock"),
      b("Assault Fitness", "assaultfitness.com", "67", "8h", "AirRunner Elite launch"),
      b("Xebex", "xebexfitness.com", "34", "12h", "Air Rower restock"),
      b("TRX", "trxtraining.com", "189", "4h", "Pro4 System restock"),
      b("BOSU", "bosu.com", "45", "7h", "NexGen balance trainer"),
      b("TriggerPoint", "tfrriggerpoint.com", "67", "5h", "GRID foam roller restock"),
      b("Theraband", "theraband.com", "123", "6h", "CLX resistance band update"),
      b("Perform Better", "performbetter.com", "567", "3h", "Mini band set restock"),
      b("Power Systems", "power-systems.com", "789", "2h", "Medicine ball restock"),
      b("Tempo", "tempo.fit", "23", "1d", "Move home gym update"),
      b("Mirror", "mirror.co", "34", "8h", "Accessories bundle refresh"),
      b("Future", "future.co", "20", "12h", "Coaching plan pricing update"),
      b("Caliber", "caliberstrong.com", "23", "2d", "App subscription update"),
      b("Ladder", "ladder.sport", "45", "5h", "Whey protein new flavour"),
      b("Momentous", "livemomentous.com", "89", "3h", "Creatine restock"),
      b("Transparent Labs", "transparentlabs.com", "234", "2h", "Bulk pre-workout new flavour"),
      b("Jacked Factory", "jackedfactory.com", "145", "4h", "Nitrosurge restock"),
      b("Ghost Lifestyle", "ghostlifestyle.com", "178", "3h", "Legend V3 new collab"),
      b("Gorilla Mind", "gorillamind.com", "89", "5h", "Sigma pre-workout launch"),
      b("Raw Nutrition", "rawnutrition.com", "123", "4h", "Thavage pre-workout restock"),
      b("Alani Nu", "alaninu.com", "234", "2h", "Energy drink new flavour"),
      b("Bloom Nutrition", "bloomnu.com", "145", "3h", "Greens powder restock"),
      b("1st Phorm", "1stphorm.com", "567", "1h", "Level-1 protein new flavour"),
      b("Legion Athletics", "legionathletics.com", "178", "4h", "Pulse pre-workout restock"),
      b("Kaged", "kfrged.com", "234", "3h", "Pre-Kaged Elite launch"),
      b("Optimum Nutrition", "optimumnutrition.com", "456", "2h", "Gold Standard restock"),
      b("MyProtein", "myprotein.com", "3,456", "1h", "Impact Whey sale -30%"),
      b("Bulk", "bulk.com", "2,345", "1h", "Pure Whey new flavour"),
      b("PEScience", "pescience.com", "123", "5h", "Select Protein restock"),
      b("Redcon1", "redcon1.com", "234", "3h", "Total War new flavour"),
      b("BPN", "bareperformancenutrition.com", "145", "4h", "Flight pre-workout restock"),
      b("XWERKS", "xwerks.com", "67", "6h", "Grow whey new flavour"),
      b("Swolverine", "swolverine.com", "89", "5h", "Clean Carbs restock"),
      b("Cellucor", "cellucor.com", "178", "3h", "C4 Ultimate new flavour"),
      b("Rogue Echo", "roguefrfitness.com/echo", "45", "5h", "Echo Bike V3 restock"),
      b("Lacrosse Ball", "roguefrfitness.com/lacrosse", "23", "8h", "Mobility ball 2-pack restock"),
    ],
  },
  {
    id: "jewellery",
    label: "Jewellery & Accessories",
    brands: [
      b("Mejuri", "mejuri.com", "567", "2h", "Croissant Dome ring restock"),
      b("Gorjana", "gorjana.com", "789", "3h", "Parker necklace new length"),
      b("Ana Luisa", "analuisa.com", "345", "4h", "Gold vermeil hoops restock"),
      b("Vitaly", "vitalydesign.com", "234", "5h", "Cuban chain new finish"),
      b("Missoma", "missoma.com", "456", "3h", "Lucy Williams collab restock"),
      b("Monica Vinader", "monicavinader.com", "678", "2h", "Siren pendant new stone"),
      b("Jenny Bird", "jenny-bird.com", "312", "4h", "Puffy Heart earrings restock"),
      b("Kendra Scott", "kendrascott.com", "1,234", "1h", "Elisa necklace new colour"),
      b("BaubleBar", "baublebar.com", "2,345", "2h", "Custom nameplate restock"),
      b("Uncommon James", "uncommonjames.com", "345", "5h", "Hayride necklace restock"),
      b("Brilliant Earth", "brilliantearth.com", "3,456", "1h", "Lab diamond new cuts"),
      b("Catbird", "catbirdnyc.com", "567", "4h", "Threadbare ring restock"),
      b("Aurate", "auratenewyork.com", "345", "3h", "Infinity hoops restock"),
      b("Stone and Strand", "stoneandstrand.com", "423", "5h", "Diamond Lexicon update"),
      b("Ring Concierge", "ringconcierge.com", "289", "6h", "Tennis bracelet restock"),
      b("Dorsey", "dorfrsey.com", "123", "4h", "Riviere necklace new colour"),
      b("SOKO", "shopsoko.com", "234", "5h", "Twisted dash studs restock"),
      b("Able", "ablefr.com", "312", "3h", "Cuff bracelet new finish"),
      b("Nisolo", "nisolo.com", "267", "4h", "Everyday leather tote restock"),
      b("Sezane", "sezane.com", "789", "2h", "Scott bag new colour"),
      b("Cuyana", "cuyana.com", "234", "5h", "Classic tote new colour"),
      b("Dagne Dover", "dfragnedover.com", "312", "3h", "Landon Carryall restock"),
      b("Senreve", "senreve.com", "145", "6h", "Maestra bag new colour"),
      b("Polene", "polfrene-paris.com", "89", "7h", "Numero Un Nano restock"),
      b("Mansur Gavriel", "mansurgavriel.com", "234", "4h", "Bucket bag new colour"),
      b("Cult Gaia", "cultgaia.com", "345", "3h", "Ark bag restock"),
      b("JW Pei", "jwpei.com", "178", "5h", "Gabbi bag new colour"),
      b("Telfar", "tfrelfar.net", "56", "1d", "Shopping Bag drop announced"),
      b("Brandon Blackwood", "brandonblackwood.com", "89", "8h", "Trunk bag restock"),
      b("Staud", "stfraud.clothing", "234", "4h", "Moon bag new colour"),
      b("By Far", "byfrfrfar.com", "312", "3h", "Rachel bag restock"),
      b("Nanushka", "nanushka.com", "456", "5h", "Vegan leather bag update"),
      b("Loeffler Randall", "loefflerrandall.com", "267", "4h", "Penny knot mule restock"),
      b("Brother Vellies", "brothervellies.com", "145", "6h", "Cloud sock boot restock"),
      b("Rag & Bone", "rag-bone.com", "1,567", "2h", "Field Messenger bag launch"),
      b("AllSaints", "allsaints.com", "2,345", "1h", "Balfern jacket restock"),
      b("COS", "cos.com", "1,890", "2h", "Oversized tote new colour"),
      b("& Other Stories", "stories.com", "3,456", "1h", "Leather bag new styles"),
      b("Arket", "arfrket.com", "1,234", "3h", "Canvas tote restock"),
      b("Everlane", "everlane.com", "789", "2h", "Day Market Tote restock"),
      b("Reformation", "thereformation.com", "1,456", "3h", "Bucket bag launch"),
      b("Girlfriend Collective", "girlfriend.com", "345", "4h", "Recycled tote restock"),
      b("For Days", "fordays.com", "123", "7h", "Take Back Bag update"),
      b("Pangaia", "thepangaia.com", "234", "5h", "Padded tote new colour"),
      b("Ministry of Supply", "ministryofsupply.com", "178", "4h", "Aero Dress Shirt restock"),
      b("M.M.LaFleur", "mmlafleur.com", "345", "3h", "Jardigan restock"),
      b("Argent", "argentwork.com", "89", "8h", "Power blazer new colour"),
      b("Of Mercer", "ofmercer.com", "67", "1d", "Franklin top restock"),
      b("Universal Standard", "universalstandard.com", "456", "3h", "Geneva dress restock"),
      b("The Row", "therow.com", "234", "6h", "Margaux bag restock"),
    ],
  },
  {
    id: "mobility",
    label: "Automotive & Mobility",
    brands: [
      b("Cowboy", "cowboy.com", "23", "1d", "Cowboy 4 ST price update"),
      b("VanMoof", "vanmoof.com", "34", "2d", "S5 parts restock"),
      b("Lectric", "lectricebikes.com", "45", "4h", "XP 3.0 new colour"),
      b("RadPower", "radpowerbikes.com", "67", "3h", "RadRover 6 Plus restock"),
      b("Super73", "super73.com", "56", "5h", "S2 new colourway"),
      b("Cake", "ridecake.com", "23", "1d", "Osa Flex restock"),
      b("Niu", "niu.com", "34", "8h", "KQi3 Pro scooter update"),
      b("Gogoro", "gogoro.com", "45", "7h", "Smartscooter new colour"),
      b("Lime", "li.me/shop", "67", "5h", "Merch collection update"),
      b("Bird", "shop.bird.co", "34", "6h", "Birdie scooter accessories"),
      b("Segway", "store.segway.com", "89", "3h", "Ninebot GT2 launch"),
      b("Boosted", "boostedboards.com", "23", "2d", "Legacy parts restock"),
      b("Evolve Skateboards", "evolveskateboardsusa.com", "34", "1d", "GTR2 Carbon restock"),
      b("Meepo", "meepoboard.com", "56", "4h", "Hurricane Ultra launch"),
      b("Backfire", "backfireboards.com", "34", "6h", "Zealot S2 restock"),
      b("Exway", "exwayboard.com", "45", "5h", "Atlas Pro update"),
      b("WowGo", "wowgoboard.com", "34", "7h", "Pioneer 4 launch"),
      b("Ownboard", "ownboard.net", "23", "8h", "Zeus Pro restock"),
      b("Hovsco", "hovsco.com", "45", "4h", "HovAlpha new colour"),
      b("Aventon", "aventon.com", "67", "3h", "Aventure.2 restock"),
      b("Ride1Up", "ride1up.com", "34", "5h", "Turris new colour"),
      b("Juiced Bikes", "juicedbikes.com", "56", "4h", "Scorpion X2 restock"),
      b("Ariel Rider", "arielrider.com", "34", "6h", "Grizzly V2 new colour"),
      b("Wing Bikes", "wingbikes.com", "23", "8h", "Freedom X2 launch"),
      b("Batch Bicycles", "batchbicycles.com", "45", "7h", "E-Commuter restock"),
      b("Priority Bicycles", "prioritybicycles.com", "56", "5h", "Current e-bike update"),
      b("State Bicycle", "statebicycle.com", "234", "3h", "Black Label V3 restock"),
      b("Retrospec", "retrospec.com", "345", "2h", "Beaumont Rev new colour"),
      b("Pure Cycles", "purecycles.com", "178", "4h", "Volta e-bike restock"),
      b("Sole Bicycles", "solebicycles.com", "89", "6h", "El Tigre restock"),
      b("Woom Bikes", "woom.com", "56", "5h", "Woom 4 new colour"),
      b("Frog Bikes", "frogbikes.com", "67", "4h", "Frog 55 restock"),
      b("Islabikes", "islabikes.com", "34", "1d", "Beinn 20 update"),
      b("Commencal", "commencal.com", "234", "3h", "Meta AM V5 launch"),
      b("YT Industries", "yt-industries.com", "145", "5h", "Capra 29 new spec"),
      b("Canyon", "canyon.com", "456", "2h", "Spectral 125 CF launch"),
      b("Ribble", "ribblecycles.co.uk", "312", "3h", "Endurance SL new build"),
      b("Factor Bikes", "factorbikes.com", "34", "1d", "Ostro VAM new colour"),
      b("Cervelo", "cervelo.com", "67", "6h", "S5 Disc new colourway"),
      b("Specialized", "specialized.com", "89", "4h", "Merch collection update"),
      b("Trek", "trekbikes.com", "123", "3h", "Apparel summer collection"),
      b("Giant", "giant-bicycles.com", "78", "5h", "Gear accessories restock"),
      b("Cannondale", "cannondale.com", "67", "4h", "Urban apparel refresh"),
      b("Santa Cruz", "santacruzbicycles.com", "156", "3h", "Megatower V2 launch"),
      b("Yeti Cycles", "yeticycles.com", "89", "5h", "SB160 new colour"),
      b("Evil Bikes", "evil-bikes.com", "45", "7h", "Offering V3 launch"),
      b("Pivot", "pivotcycles.com", "78", "6h", "Firebird new spec"),
      b("Ibis", "ibiscycles.com", "56", "5h", "Ripmo V3 restock"),
      b("Niner", "ninerbikes.com", "67", "4h", "RIP 9 RDO update"),
      b("Guerrilla Gravity", "guerrillagravity.com", "34", "8h", "Smash new colourway"),
    ],
  },
];

// All brands flat
export const ALL_BRANDS = VERTICALS.flatMap((v) => v.brands);

// Total product count across all tracked stores
export const TOTAL_PRODUCTS = ALL_BRANDS.reduce((sum, b) => {
  const num = parseInt(b.products.replace(/,/g, ""), 10);
  return sum + (isNaN(num) ? 0 : num);
}, 0);

// Brand names for marquee
export const BRAND_NAMES = ALL_BRANDS.map((b) => b.name);

// Logo-style brand wordmarks with unique typography
export const BRAND_WORDMARKS: { name: string; style: string }[] = [
  // Fashion
  { name: "GYMSHARK", style: "font-bold tracking-wider" },
  { name: "FASHION NOVA", style: "font-black tracking-wide text-[11px]" },
  { name: "SKIMS", style: "font-bold tracking-[0.3em]" },
  { name: "alo", style: "font-light tracking-[0.4em] uppercase" },
  { name: "KITH", style: "font-black tracking-[0.2em]" },
  { name: "FIGS", style: "font-black tracking-[0.3em]" },
  { name: "allbirds", style: "font-medium lowercase" },
  { name: "Vuori", style: "font-medium" },
  { name: "Rhone", style: "font-semibold tracking-wide" },
  { name: "TRUE CLASSIC", style: "font-bold tracking-wider text-[11px]" },
  { name: "REPRESENT", style: "font-black tracking-[0.15em]" },
  { name: "MVMT", style: "font-bold tracking-[0.3em]" },
  { name: "AWAY", style: "font-bold tracking-[0.25em]" },
  { name: "Chubbies", style: "font-bold" },
  { name: "SAVAGE X", style: "font-black tracking-wider text-[11px]" },
  { name: "OBEY", style: "font-black tracking-[0.35em]" },
  { name: "the hundreds", style: "font-bold lowercase tracking-wide" },
  // Beauty
  { name: "FENTY BEAUTY", style: "font-bold tracking-widest text-[11px]" },
  { name: "rare beauty", style: "font-medium lowercase italic" },
  { name: "KYLIE", style: "font-bold tracking-[0.35em]" },
  { name: "Glossier", style: "font-medium italic" },
  { name: "ColourPop", style: "font-bold" },
  { name: "HISMILE", style: "font-black tracking-wider text-[11px]" },
  { name: "OLAPLEX", style: "font-bold tracking-[0.2em]" },
  { name: "Dr. Squatch", style: "font-bold" },
  { name: "ritual", style: "font-medium lowercase" },
  { name: "AG1", style: "font-black tracking-[0.2em]" },
  { name: "cocokind", style: "font-light lowercase tracking-wide" },
  { name: "PIXI", style: "font-bold tracking-[0.4em]" },
  { name: "native", style: "font-semibold lowercase" },
  { name: "KOPARI", style: "font-medium tracking-[0.3em]" },
  { name: "prose", style: "font-light lowercase italic tracking-wider" },
  { name: "hims", style: "font-bold lowercase" },
  // Home
  { name: "RUGGABLE", style: "font-medium tracking-[0.2em]" },
  { name: "casper", style: "font-bold lowercase" },
  { name: "Stanley 1913", style: "font-semibold" },
  { name: "BROOKLINEN", style: "font-medium tracking-wide" },
  { name: "YETI", style: "font-black tracking-[0.25em]" },
  { name: "Ooni", style: "font-bold" },
  { name: "Peak Design", style: "font-semibold" },
  { name: "Keychron", style: "font-medium" },
  { name: "PURPLE", style: "font-black tracking-[0.15em]" },
  { name: "article", style: "font-light lowercase tracking-[0.3em]" },
  { name: "TRAEGER", style: "font-bold tracking-wider" },
  { name: "Snow Peak", style: "font-medium italic" },
  { name: "TIMBUK2", style: "font-black tracking-wide text-[11px]" },
  // Food
  { name: "LIQUID DEATH", style: "font-black tracking-wider text-[11px]" },
  { name: "huel", style: "font-bold lowercase" },
  { name: "Magic Spoon", style: "font-bold" },
  { name: "Owala", style: "font-bold" },
  { name: "Fellow", style: "font-medium" },
  { name: "HexClad", style: "font-semibold" },
  { name: "olipop", style: "font-bold lowercase tracking-wide" },
  { name: "GRAZA", style: "font-black tracking-[0.3em]" },
  { name: "ghia", style: "font-light lowercase italic" },
  { name: "Blue Bottle", style: "font-medium" },
  // Electronics
  { name: "NOMAD", style: "font-bold tracking-[0.3em]" },
  { name: "RIDGE", style: "font-black tracking-[0.25em]" },
  { name: "secretlab", style: "font-bold lowercase" },
  { name: "Jackery", style: "font-semibold" },
  { name: "NANOLEAF", style: "font-medium tracking-[0.15em]" },
  { name: "RAZER", style: "font-black tracking-[0.2em]" },
  { name: "Raspberry Pi", style: "font-medium" },
  { name: "Bombas", style: "font-bold" },
  { name: "Rothy's", style: "font-medium italic" },
  { name: "MOMENT", style: "font-medium tracking-[0.2em]" },
  { name: "CORSAIR", style: "font-bold tracking-[0.25em]" },
  { name: "SENNHEISER", style: "font-light tracking-[0.4em] uppercase text-[10px]" },
  { name: "dbrand", style: "font-black lowercase" },
  { name: "nothing", style: "font-light lowercase tracking-[0.2em]" },
  { name: "Bambu Lab", style: "font-semibold" },
  { name: "ANKER", style: "font-bold tracking-[0.2em]" },
  { name: "teenage engineering", style: "font-light lowercase tracking-wider text-[10px]" },
  { name: "Oura", style: "font-medium italic" },
  { name: "Insta360", style: "font-semibold" },
  { name: "remarkable", style: "font-light lowercase tracking-[0.3em]" },
  // Sports & Outdoors
  { name: "HOKA", style: "font-black tracking-[0.2em]" },
  { name: "On", style: "font-bold tracking-[0.4em] uppercase" },
  { name: "SALOMON", style: "font-bold tracking-[0.25em]" },
  { name: "ARC'TERYX", style: "font-medium tracking-[0.2em]" },
  { name: "patagonia", style: "font-bold lowercase" },
  { name: "THE NORTH FACE", style: "font-black tracking-wider text-[10px]" },
  { name: "Osprey", style: "font-semibold italic" },
  { name: "SITKA", style: "font-black tracking-[0.3em]" },
  { name: "Filson", style: "font-bold" },
  // Kids & Baby
  { name: "Lovevery", style: "font-medium" },
  { name: "NUGGET", style: "font-black tracking-[0.25em]" },
  { name: "KiwiCo", style: "font-bold" },
  { name: "Kyte Baby", style: "font-light italic tracking-wide" },
  { name: "UPPAbaby", style: "font-semibold" },
  // Pets
  { name: "BARKBOX", style: "font-black tracking-wider text-[11px]" },
  { name: "wild one", style: "font-medium lowercase tracking-[0.2em]" },
  { name: "RUFFWEAR", style: "font-bold tracking-[0.2em]" },
  { name: "Litter-Robot", style: "font-semibold" },
  // Health & Fitness
  { name: "THERABODY", style: "font-bold tracking-[0.25em]" },
  { name: "ROGUE", style: "font-black tracking-[0.3em]" },
  { name: "GHOST", style: "font-black tracking-[0.35em]" },
  { name: "alani nu", style: "font-medium lowercase" },
  { name: "MYPROTEIN", style: "font-bold tracking-wide" },
  // Jewellery & Accessories
  { name: "mejuri", style: "font-light lowercase tracking-[0.3em]" },
  { name: "MISSOMA", style: "font-medium tracking-[0.2em]" },
  { name: "KENDRA SCOTT", style: "font-bold tracking-wider text-[10px]" },
  { name: "Brilliant Earth", style: "font-medium italic" },
  { name: "Polene", style: "font-light tracking-[0.25em]" },
  { name: "TELFAR", style: "font-black tracking-[0.3em]" },
  // Automotive & Mobility
  { name: "SUPER73", style: "font-black tracking-[0.2em]" },
  { name: "RadPower", style: "font-bold" },
  { name: "Canyon", style: "font-semibold" },
  { name: "SANTA CRUZ", style: "font-black tracking-wider text-[10px]" },
  { name: "SPECIALIZED", style: "font-medium tracking-[0.15em]" },
];
