// ── Single source of truth for all tracked brands ──

export interface Brand {
  name: string;
  domain: string;
  products: string;
  lastUpdate: string;
  latestChange: string;
}

export interface Vertical {
  id: string;
  label: string;
  brands: Brand[];
}

// Helper to generate realistic-looking product counts and update times
function b(name: string, domain: string, products: string, lastUpdate: string, latestChange: string): Brand {
  return { name, domain, products, lastUpdate, latestChange };
}

export const VERTICALS: Vertical[] = [
  {
    id: "fashion",
    label: "Fashion",
    brands: [
      b("Gymshark", "gymshark.com", "2,847", "2h", "-12% on 4 items"),
      b("Fashion Nova", "fashionnova.com", "14,502", "1h", "38 new arrivals"),
      b("SKIMS", "skims.com", "1,923", "4h", "3 new products"),
      b("Alo Yoga", "aloyoga.com", "2,156", "2h", "14 new items"),
      b("Kith", "kith.com", "3,412", "3h", "New drop launched"),
      b("Steve Madden", "stevemadden.com", "3,671", "5h", "Seasonal sale -20%"),
      b("FIGS", "wearfigs.com", "867", "6h", "New colourway added"),
      b("Allbirds", "allbirds.com", "412", "8h", "Price increase +5%"),
      b("Bombas", "bombas.com", "1,234", "4h", "-6% on socks"),
      b("Taylor Stitch", "taylorstitch.com", "523", "6h", "Workshop sale"),
      b("OddBalls", "myoddballs.com", "345", "3h", "New prints added"),
      b("Tentree", "tentree.com", "678", "5h", "Earth collection drop"),
      b("Chubbies", "chubbies.com", "834", "7h", "Swim trunk restock"),
      b("Represent Clothing", "representclo.com", "1,123", "2h", "New season launch"),
      b("Outdoor Voices", "outdoorvoices.com", "456", "4h", "Colour refresh"),
      b("True Classic", "trueclassictees.com", "312", "3h", "Bundle pricing update"),
      b("Buck Mason", "buckmason.com", "267", "8h", "New denim line"),
      b("Vuori", "vuori.com", "1,567", "2h", "12 new styles"),
      b("Rhone", "rhone.com", "834", "5h", "Commuter collection"),
      b("Cuts Clothing", "cutsclothing.com", "189", "6h", "New crew neck"),
      b("MeUndies", "meundies.com", "567", "4h", "Print collaboration"),
      b("Stance", "stance.com", "2,345", "3h", "NBA collection update"),
      b("Happy Socks", "happysocks.com", "1,890", "5h", "Summer range"),
      b("Knix", "knix.com", "445", "7h", "Swim launch"),
      b("ThirdLove", "thirdlove.com", "312", "6h", "New fit finder"),
      b("Savage X Fenty", "savagex.com", "2,678", "1h", "Monthly drop"),
      b("Lunya", "lunya.co", "234", "8h", "Washable silk restock"),
      b("Rothy's", "rothys.com", "378", "4h", "New point colour"),
      b("Thursday Boots", "thursdayboots.com", "156", "1d", "Captain restock"),
      b("Greats", "greats.com", "89", "12h", "Royale new colour"),
      b("Vessi", "vessi.com", "123", "6h", "Waterproof Weekend"),
      b("MVMT", "mvmtwatches.com", "456", "5h", "New chronograph"),
      b("Daniel Wellington", "danielwellington.com", "678", "4h", "Icon collection"),
      b("Away", "awaytravel.com", "234", "8h", "Aluminium restock"),
      b("Monos", "monos.com", "167", "7h", "New Metro colour"),
      b("Bellroy", "bellroy.com", "312", "5h", "Transit collection"),
      b("Ridge Wallet", "ridgewallet.com", "234", "4h", "New titanium finish"),
      b("Ekster", "ekster.com", "145", "6h", "Parliament wallet update"),
      // ── New fashion brands ──
      b("Todd Snyder", "toddsnyder.com", "1,456", "3h", "Italian leather collection"),
      b("Marine Layer", "marinelayer.com", "734", "5h", "Re-Spun tees restock"),
      b("Public Rec", "publicrec.com", "145", "8h", "All Day Every Day new colour"),
      b("Western Rise", "westernrise.com", "87", "1d", "Diversion pant update"),
      b("Mack Weldon", "mackweldon.com", "423", "3h", "Silver underwear restock"),
      b("OBEY Clothing", "obeyclothing.com", "1,867", "2h", "Summer graphic tees"),
      b("The Hundreds", "thehundreds.com", "2,134", "4h", "Adam Bomb collab drop"),
      b("Only NY", "onlyny.com", "312", "6h", "Fishing hat restock"),
      b("Koio", "koio.co", "78", "12h", "Capri triple white launch"),
      b("Oliver Cabell", "olivercabell.com", "134", "5h", "Low 1 new colourway"),
      b("Quay Australia", "quayaustralia.com", "567", "2h", "-15% on polarized styles"),
      b("Vincero", "vincerowatches.com", "189", "7h", "Chrono S new dial"),
    ],
  },
  {
    id: "beauty",
    label: "Beauty & Wellness",
    brands: [
      b("Fenty Beauty", "fentybeauty.com", "1,241", "1h", "New collection launched"),
      b("Rare Beauty", "rarebeauty.com", "534", "3h", "5 new shades"),
      b("Kylie Cosmetics", "kyliecosmetics.com", "687", "4h", "Lip kit restocked"),
      b("Glossier", "glossier.com", "312", "8h", "-8% on skincare"),
      b("ColourPop", "colourpop.com", "3,891", "2h", "Disney collab drop"),
      b("Hismile", "hismile.com", "156", "6h", "New flavour added"),
      b("Olaplex", "olaplex.com", "89", "1d", "Bundle pricing updated"),
      b("Tropic Skincare", "tropicskincare.com", "234", "5h", "3 products restocked"),
      b("The Beauty Chef", "thebeautychef.com", "67", "12h", "New supplement line"),
      b("Summer Fridays", "summerfridays.com", "98", "7h", "Limited edition SPF"),
      b("Jeffree Star Cosmetics", "jeffreestarcosmetics.com", "567", "3h", "Mystery box sale"),
      b("Iconic London", "iconiclondoninc.com", "234", "5h", "Illuminator restock"),
      b("Kosas Cosmetics", "kfrancis.kosas.com", "145", "6h", "Tinted oil update"),
      b("Glow Recipe", "glowrecipe.com", "178", "4h", "Watermelon set"),
      b("Dr. Squatch", "drsquatch.com", "312", "2h", "New bar scents"),
      b("Harry's", "harrys.com", "189", "5h", "Shave set refresh"),
      b("Ouai", "theouai.com", "156", "7h", "New treatment mask"),
      b("Function of Beauty", "functionofbeauty.com", "78", "8h", "Body line expansion"),
      b("Ritual", "ritual.com", "45", "6h", "Protein powder launch"),
      b("Athletic Greens", "drinkag1.com", "34", "1d", "Travel pack update"),
      b("Mud/Wtr", "mudwtr.com", "56", "8h", ":rest blend restock"),
      b("Vital Proteins", "vitalproteins.com", "234", "4h", "Collagen bars"),
      b("Quip", "getquip.com", "89", "1d", "Smart brush update"),
      b("Snow Teeth Whitening", "trysnow.com", "67", "6h", "LED kit refresh"),
      b("Blueland", "blueland.com", "78", "5h", "Laundry tablets"),
      // ── New beauty brands ──
      b("Cocokind", "cocokind.com", "112", "3h", "Ceramide barrier serum launch"),
      b("Pixi Beauty", "pixibeauty.com", "456", "2h", "Glow Tonic bundle update"),
      b("Stila Cosmetics", "stilacosmetics.com", "389", "5h", "Glitter & Glow restock"),
      b("Beauty Bakerie", "beautybakerie.com", "234", "4h", "Flour Setting Powder new shade"),
      b("Josie Maran", "josiemaran.com", "178", "6h", "Argan oil holiday set"),
      b("The Honey Pot", "thehoneypot.co", "145", "3h", "New herbal wash"),
      b("Lumin", "luminskin.com", "67", "8h", "Dark circle defense restock"),
      b("Geologie", "geologie.com", "34", "1d", "Personalized routine refresh"),
      b("Tiege Hanley", "tifriegehanley.com", "56", "5h", "Level 2 system update"),
      b("Oars + Alps", "oarsandalps.com", "89", "7h", "Aluminum-free deodorant restock"),
      b("Native", "nativecos.com", "234", "2h", "-20% on body wash"),
      b("Kopari", "koparibeauty.com", "167", "4h", "Coconut deodorant new scent"),
      b("Prose", "prose.com", "45", "12h", "Custom haircare formula update"),
      b("Hims & Hers", "forhims.com", "312", "1h", "New skincare line launched"),
      b("Moon Juice", "moonjuice.com", "89", "6h", "SuperYou restock"),
      b("Golde", "golde.co", "56", "8h", "Matcha turmeric latte new flavour"),
      b("Hum Nutrition", "humnutrition.com", "78", "5h", "Gummy vitamin expansion"),
      b("Olly", "olly.com", "145", "3h", "Sleep gummy restock"),
      b("Pura", "pura.com", "234", "2h", "New fragrance collaboration"),
      b("Vitruvi", "vitruvi.com", "67", "7h", "Stone diffuser new colour"),
      b("Saje Natural Wellness", "saje.com", "312", "4h", "Essential oil blend launch"),
      b("Grove Collaborative", "grove.co", "1,567", "1h", "Spring cleaning bundle"),
      b("Tru Earth", "tru.earth", "34", "1d", "Laundry strips new scent"),
      b("Lume", "lumedeodorant.com", "123", "3h", "Whole body deodorant restock"),
      b("Burst Oral Care", "bfrst.com", "45", "8h", "Sonic brush head refill"),
    ],
  },
  {
    id: "home",
    label: "Home & Garden",
    brands: [
      b("Ruggable", "ruggable.com", "4,123", "1h", "48 new designs"),
      b("Casper", "casper.com", "234", "3h", "Mattress sale -15%"),
      b("Arhaus", "arhaus.com", "5,671", "2h", "New outdoor collection"),
      b("Stanley 1913", "stanley1913.com", "567", "4h", "New tumbler colour"),
      b("Brooklinen", "brooklinen.com", "456", "6h", "Seasonal bundle update"),
      b("Parachute Home", "parachutehome.com", "389", "5h", "Price drop on linens"),
      b("Boll & Branch", "bollandbranch.com", "312", "8h", "New thread count line"),
      b("Fast Growing Trees", "fastgrowingtrees.com", "1,456", "3h", "Spring stock update"),
      b("Leesa", "leesa.com", "123", "1d", "Hybrid mattress refresh"),
      b("Burrow", "burrow.com", "345", "4h", "Nomad sofa new colour"),
      b("Article", "article.com", "2,345", "2h", "Mid-century restock"),
      b("Outer", "liveouter.com", "89", "8h", "Outdoor sofa update"),
      b("Yeti", "yeti.com", "678", "3h", "New Rambler colour"),
      b("Hydro Flask", "hydroflask.com", "456", "5h", "Wide Mouth restock"),
      b("Solo Stove", "solostove.com", "123", "6h", "Mesa tabletop fire pit"),
      b("Ooni", "ooni.com", "89", "7h", "Koda 2 Max launch"),
      b("Rumpl", "rumpl.com", "234", "4h", "National Parks series"),
      b("Peak Design", "peakdesign.com", "312", "5h", "Travel Backpack V2"),
      b("Nomatic", "nomatic.com", "178", "6h", "Navigator expansion"),
      b("Elgato", "elgato.com", "145", "4h", "Stream Deck Neo"),
      b("Keychron", "keychron.com", "234", "3h", "Q series restock"),
      b("Secretlab", "secretlab.co", "156", "6h", "TITAN Evo new fabric"),
      // ── New home brands ──
      b("Purple", "purple.com", "267", "2h", "Hybrid Premier mattress restock"),
      b("Joybird", "joybird.com", "1,234", "3h", "Sectional new fabric options"),
      b("Floyd", "floydhome.com", "89", "8h", "The Bed frame walnut restock"),
      b("Interior Define", "interiordefine.com", "567", "5h", "Custom sofa lead time update"),
      b("Neighbor", "neighbor.com", "45", "1d", "Performance mattress price drop -10%"),
      b("RTIC", "rticoutdoors.com", "456", "2h", "Tumbler new colours"),
      b("Corkcicle", "corkcicle.com", "345", "4h", "Canteen restock"),
      b("Larq", "lfrqcom.myshopify.com", "67", "7h", "Self-cleaning bottle V2"),
      b("S'well", "swell.com", "289", "3h", "Traveler collection launch"),
      b("Traeger", "traeger.com", "312", "5h", "Ironwood pellet grill update"),
      b("Breeo", "breeo.co", "78", "8h", "X Series fire pit restock"),
      b("Gozney", "gozney.com", "56", "6h", "Dome S1 pizza oven launch"),
      b("BioLite", "bfrioliteenergy.com", "145", "4h", "CampStove 2 bundle"),
      b("Snow Peak", "snowpeak.com", "567", "3h", "Titanium cookware restock"),
      b("Big Agnes", "bigagnes.com", "423", "5h", "Copper Spur tent update"),
      b("Sea to Summit", "seatosummit.com", "678", "2h", "Sleeping pad new model"),
      b("Aer", "aersf.com", "123", "7h", "Travel Pack 3 restock"),
      b("Timbuk2", "timbuk2.com", "456", "3h", "Classic Messenger refresh"),
      b("Chrome Industries", "chromeindustries.com", "345", "5h", "Citizen new colourway"),
      b("Society6", "society6.com", "12,456", "1h", "8,400 new artist prints"),
      b("Sandmarc", "sandmarc.com", "89", "8h", "iPhone lens kit update"),
      b("Polaroid", "polaroid.com", "178", "4h", "Go Generation 2 camera launch"),
      b("Weber", "weber.com", "345", "6h", "Spirit series price drop -12%"),
      b("Maiden Home", "maidenhome.com", "67", "1d", "Sullivan sofa new fabric"),
      b("Incase", "incase.com", "234", "5h", "Icon Backpack restock"),
      b("Tortuga", "tortugabackpacks.com", "45", "12h", "Outbreaker 45L update"),
      b("Waterfield Designs", "sfbags.com", "156", "3h", "Air Porter carry-on launch"),
      b("Minaal", "minaal.com", "34", "2d", "Carry-on 3.0 restock"),
    ],
  },
  {
    id: "food",
    label: "Food & Beverage",
    brands: [
      b("Liquid Death", "liquiddeath.com", "156", "5h", "New flavour launched"),
      b("Huel", "huel.com", "178", "4h", "Price drop -10%"),
      b("Magic Spoon", "magicspoon.com", "42", "1d", "New cereal bars"),
      b("Death Wish Coffee", "deathwishcoffee.com", "89", "8h", "Reserve blend added"),
      b("Red Bull Shop", "redbullshopus.com", "312", "6h", "New merch collection"),
      b("Fly by Jing", "flybyjing.com", "67", "3h", "Gift set updated"),
      b("Owala", "owala.com", "145", "2h", "FreeSip new colours"),
      b("Stumptown Coffee", "stumptowncoffee.com", "78", "7h", "Subscription pricing change"),
      b("Partake Foods", "partakefoods.com", "34", "1d", "New cookie flavour"),
      b("Heatonist", "heatonist.com", "256", "4h", "Hot Ones bundle"),
      b("Milk Bar", "milkbarstore.com", "123", "3h", "Birthday cake restock"),
      b("Chomps", "chomps.com", "67", "6h", "New original flavour"),
      b("Soylent", "soylent.com", "45", "8h", "Complete Protein update"),
      b("Daily Harvest", "daily-harvest.com", "312", "2h", "Summer smoothies"),
      b("Our Place", "fromourplace.com", "89", "5h", "Always Pan 2.0 Sage"),
      b("Caraway", "carawayhome.com", "134", "6h", "Bakeware Set Navy"),
      b("Made In Cookware", "madeincookware.com", "234", "4h", "Carbon steel restock"),
      b("HexClad", "hexclad.com", "89", "7h", "Gordon Ramsay set"),
      b("Fellow", "fellowproducts.com", "156", "3h", "Stagg EKG update"),
      b("Aeropress", "aeropress.com", "34", "1d", "Clear model launch"),
      b("Chemex", "chemexcoffeemaker.com", "23", "2d", "Glass handle restock"),
      // ── New food brands ──
      b("Chamberlain Coffee", "chamberlaincoffee.com", "78", "3h", "New matcha blend launch"),
      b("Levain Bakery", "levainbakery.com", "45", "5h", "Seasonal cookie box"),
      b("Splendid Spoon", "splendidspoon.com", "89", "4h", "Smoothie bowl new flavours"),
      b("Sakara Life", "sakara.com", "134", "2h", "Meal delivery menu refresh"),
      b("ButcherBox", "butcherbox.com", "67", "8h", "Grass-fed beef bundle update"),
      b("Crowd Cow", "crowdcow.com", "345", "3h", "Wagyu restock"),
      b("Snake River Farms", "snakeriverfarms.com", "156", "6h", "American Wagyu brisket restock"),
      b("Thrive Market", "thrivemarket.com", "4,567", "1h", "2,300 products price updated"),
      b("Misfits Market", "misfitsmarket.com", "1,234", "2h", "Organic produce box refresh"),
      b("Great Jones", "greatjonesgoods.com", "45", "1d", "Dutchess new colour"),
      b("Misen", "misen.com", "89", "5h", "Chef's knife restock"),
      b("Material Kitchen", "materialkitchen.com", "67", "7h", "reBoard cutting board launch"),
      b("Baratza", "baratza.com", "34", "12h", "Encore ESP grinder launch"),
      b("Flair Espresso", "flairespresso.com", "23", "8h", "Pro 2 new colour"),
      b("Hario", "hfrario-usa.com", "145", "4h", "V60 drip kettle restock"),
      b("Timemore", "timemore.com", "78", "6h", "C3 grinder new colour"),
      b("Graza", "grfraza.co", "34", "3h", "Sizzle olive oil restock"),
      b("Ghia", "drinkghia.com", "23", "5h", "Non-alcoholic aperitivo bundle"),
      b("Olipop", "drinkolipop.com", "56", "2h", "New cherry cola flavour"),
      b("Poppi", "drinkpoppi.com", "45", "4h", "Strawberry lemon restock"),
      b("Beekeeper's Naturals", "beekeepersnaturals.com", "78", "7h", "Propolis throat spray bundle"),
      b("MUDWTR", "mudwtr.com", "56", "8h", ":energy blend launch"),
      b("Four Sigmatic", "foursigmatic.com", "123", "3h", "Mushroom coffee restock"),
      b("Laird Superfood", "lairdsuperfood.com", "89", "6h", "Creamer new flavour"),
      b("Trade Coffee", "dfrrinktrade.com", "567", "1h", "New roaster partner added"),
      b("Verve Coffee", "vervecoffee.com", "67", "5h", "Streetlevel blend restock"),
      b("Intelligentsia", "intelligentsia.com", "89", "4h", "Black Cat espresso update"),
      b("Counter Culture", "counterculturecoffee.com", "45", "8h", "Hologram decaf restock"),
      b("Blue Bottle Coffee", "bluebottlecoffee.com", "78", "3h", "Subscription gift set launch"),
    ],
  },
  {
    id: "electronics",
    label: "Electronics & Tech",
    brands: [
      b("Nomad Goods", "nomadgoods.com", "189", "3h", "iPhone 16 cases"),
      b("Ridge Wallet", "ridgewallet.com", "234", "4h", "New titanium finish"),
      b("Cowboy", "cowboy.com", "23", "1d", "E-bike price update"),
      b("Secretlab", "secretlab.co", "156", "6h", "New TITAN Evo"),
      b("Pela Case", "pelacase.com", "312", "5h", "Compostable range expanded"),
      b("Master & Dynamic", "masterdynamic.com", "89", "8h", "New wireless model"),
      b("Jackery", "jackery.com", "78", "3h", "Solar panel bundle"),
      b("Moment", "shopmoment.com", "678", "4h", "CineBloom restock"),
      b("Nanoleaf", "nanoleaf.me", "45", "7h", "Skylight panel launch"),
      b("Elgato", "elgato.com", "145", "4h", "Stream Deck update"),
      b("Loop Earplugs", "loopearplugs.com", "67", "6h", "Switch new colour"),
      b("MVMT Watches", "mvmtwatches.com", "456", "5h", "Arc Automatic"),
      b("Keychron", "keychron.com", "234", "3h", "Q1 Max restock"),
      b("Shokz", "shokz.com", "78", "8h", "OpenRun Pro 2"),
      b("RhinoShield", "rhinoshield.io", "567", "2h", "SolidSuit new designs"),
      b("Framework Laptop", "frame.work", "23", "1d", "16\" expansion cards"),
      b("Razer", "razer.com", "1,234", "1h", "Viper V3 launch"),
      b("Logitech G", "logitechg.com", "567", "3h", "Pro X Superlight 2"),
      b("Raspberry Pi", "raspberrypi.com", "89", "6h", "Pi 5 restock"),
      // ── New electronics brands ──
      b("Sennheiser", "sennheiser.com", "456", "2h", "Momentum 4 new colour"),
      b("Paperlike", "paperlike.com", "34", "8h", "iPad Pro screen protector V2"),
      b("SteelSeries", "steelseries.com", "345", "3h", "Arctis Nova Pro restock"),
      b("Corsair", "corsair.com", "1,567", "1h", "K100 RGB keyboard update"),
      b("NZXT", "nzxt.com", "234", "4h", "H7 Flow case new colour"),
      b("Fractal Design", "fractal-design.com", "145", "5h", "North case restock"),
      b("Glorious Gaming", "gloriousgaming.com", "312", "3h", "GMMK 3 launch"),
      b("Ducky", "dfruckychannel.com", "178", "6h", "One 3 new switches"),
      b("Arduino", "store.arduino.cc", "89", "7h", "UNO R4 WiFi restock"),
      b("System76", "system76.com", "34", "1d", "Pangolin laptop refresh"),
      b("Purism", "puri.sm", "23", "2d", "Librem 14 V2 update"),
      b("Pine64", "pine64.org", "45", "12h", "PinePhone Pro restock"),
      b("Native Union", "nativeunion.com", "156", "4h", "Dock wireless charger update"),
      b("Anker", "anker.com", "2,345", "1h", "Prime Day bundle pricing"),
      b("Twelve South", "twelvesouth.com", "89", "5h", "BookArc new finish"),
      b("CalDigit", "caldigit.com", "45", "8h", "TS4 Thunderbolt dock restock"),
      b("Dbrand", "dbrand.com", "4,567", "2h", "Teardown skin new devices"),
      b("Analogue", "analogue.co", "23", "2d", "Pocket limited edition"),
      b("Teenage Engineering", "teenage.engineering", "67", "3h", "EP-133 restock"),
      b("Nothing", "nothing.tech", "34", "5h", "Ear (a) new colour"),
      b("Remarkable", "remarkable.com", "23", "1d", "Paper Pro accessories launch"),
      b("Supernote", "supernote.com", "34", "8h", "Nomad case update"),
      b("Boox", "shop.boox.com", "78", "4h", "Tab Ultra C Pro launch"),
      b("Oura", "ouraring.com", "45", "6h", "Ring Gen 4 new finish"),
      b("Whoop", "whoop.com", "34", "7h", "4.0 band new colours"),
      b("Bambu Lab", "bambulab.com", "56", "3h", "A1 Mini bundle restock"),
      b("Prusa", "prusa3d.com", "89", "5h", "MK4S upgrade kit launch"),
      b("Creality", "store.creality.com", "234", "2h", "K1 Max new firmware bundle"),
      b("Elegoo", "elegoo.com", "178", "4h", "Saturn 4 Ultra launch"),
      b("Lume Pad", "lfreiagear.com", "23", "1d", "Lume Pad 2 price drop -15%"),
      b("Insta360", "store.insta360.com", "67", "3h", "X4 action cam bundle"),
    ],
  },
];

// All brands flat
export const ALL_BRANDS = VERTICALS.flatMap((v) => v.brands);

// Total product count across all tracked stores
export const TOTAL_PRODUCTS = ALL_BRANDS.reduce((sum, b) => {
  const num = parseInt(b.products.replace(/,/g, ""), 10);
  return sum + (isNaN(num) ? 0 : num);
}, 0);

// Brand names for marquee
export const BRAND_NAMES = ALL_BRANDS.map((b) => b.name);

// Logo-style brand wordmarks with unique typography
export const BRAND_WORDMARKS: { name: string; style: string }[] = [
  // Fashion
  { name: "GYMSHARK", style: "font-bold tracking-wider" },
  { name: "FASHION NOVA", style: "font-black tracking-wide text-[11px]" },
  { name: "SKIMS", style: "font-bold tracking-[0.3em]" },
  { name: "alo", style: "font-light tracking-[0.4em] uppercase" },
  { name: "KITH", style: "font-black tracking-[0.2em]" },
  { name: "FIGS", style: "font-black tracking-[0.3em]" },
  { name: "allbirds", style: "font-medium lowercase" },
  { name: "Vuori", style: "font-medium" },
  { name: "Rhone", style: "font-semibold tracking-wide" },
  { name: "TRUE CLASSIC", style: "font-bold tracking-wider text-[11px]" },
  { name: "REPRESENT", style: "font-black tracking-[0.15em]" },
  { name: "MVMT", style: "font-bold tracking-[0.3em]" },
  { name: "AWAY", style: "font-bold tracking-[0.25em]" },
  { name: "Chubbies", style: "font-bold" },
  { name: "SAVAGE X", style: "font-black tracking-wider text-[11px]" },
  { name: "OBEY", style: "font-black tracking-[0.35em]" },
  { name: "the hundreds", style: "font-bold lowercase tracking-wide" },
  // Beauty
  { name: "FENTY BEAUTY", style: "font-bold tracking-widest text-[11px]" },
  { name: "rare beauty", style: "font-medium lowercase italic" },
  { name: "KYLIE", style: "font-bold tracking-[0.35em]" },
  { name: "Glossier", style: "font-medium italic" },
  { name: "ColourPop", style: "font-bold" },
  { name: "HISMILE", style: "font-black tracking-wider text-[11px]" },
  { name: "OLAPLEX", style: "font-bold tracking-[0.2em]" },
  { name: "Dr. Squatch", style: "font-bold" },
  { name: "ritual", style: "font-medium lowercase" },
  { name: "AG1", style: "font-black tracking-[0.2em]" },
  { name: "cocokind", style: "font-light lowercase tracking-wide" },
  { name: "PIXI", style: "font-bold tracking-[0.4em]" },
  { name: "native", style: "font-semibold lowercase" },
  { name: "KOPARI", style: "font-medium tracking-[0.3em]" },
  { name: "prose", style: "font-light lowercase italic tracking-wider" },
  { name: "hims", style: "font-bold lowercase" },
  // Home
  { name: "RUGGABLE", style: "font-medium tracking-[0.2em]" },
  { name: "casper", style: "font-bold lowercase" },
  { name: "Stanley 1913", style: "font-semibold" },
  { name: "BROOKLINEN", style: "font-medium tracking-wide" },
  { name: "YETI", style: "font-black tracking-[0.25em]" },
  { name: "Ooni", style: "font-bold" },
  { name: "Peak Design", style: "font-semibold" },
  { name: "Keychron", style: "font-medium" },
  { name: "PURPLE", style: "font-black tracking-[0.15em]" },
  { name: "article", style: "font-light lowercase tracking-[0.3em]" },
  { name: "TRAEGER", style: "font-bold tracking-wider" },
  { name: "Snow Peak", style: "font-medium italic" },
  { name: "TIMBUK2", style: "font-black tracking-wide text-[11px]" },
  // Food
  { name: "LIQUID DEATH", style: "font-black tracking-wider text-[11px]" },
  { name: "huel", style: "font-bold lowercase" },
  { name: "Magic Spoon", style: "font-bold" },
  { name: "Owala", style: "font-bold" },
  { name: "Fellow", style: "font-medium" },
  { name: "HexClad", style: "font-semibold" },
  { name: "olipop", style: "font-bold lowercase tracking-wide" },
  { name: "GRAZA", style: "font-black tracking-[0.3em]" },
  { name: "ghia", style: "font-light lowercase italic" },
  { name: "Blue Bottle", style: "font-medium" },
  // Electronics
  { name: "NOMAD", style: "font-bold tracking-[0.3em]" },
  { name: "RIDGE", style: "font-black tracking-[0.25em]" },
  { name: "secretlab", style: "font-bold lowercase" },
  { name: "Jackery", style: "font-semibold" },
  { name: "NANOLEAF", style: "font-medium tracking-[0.15em]" },
  { name: "RAZER", style: "font-black tracking-[0.2em]" },
  { name: "Raspberry Pi", style: "font-medium" },
  { name: "Bombas", style: "font-bold" },
  { name: "Rothy's", style: "font-medium italic" },
  { name: "MOMENT", style: "font-medium tracking-[0.2em]" },
  { name: "CORSAIR", style: "font-bold tracking-[0.25em]" },
  { name: "SENNHEISER", style: "font-light tracking-[0.4em] uppercase text-[10px]" },
  { name: "dbrand", style: "font-black lowercase" },
  { name: "nothing", style: "font-light lowercase tracking-[0.2em]" },
  { name: "Bambu Lab", style: "font-semibold" },
  { name: "ANKER", style: "font-bold tracking-[0.2em]" },
  { name: "teenage engineering", style: "font-light lowercase tracking-wider text-[10px]" },
  { name: "Oura", style: "font-medium italic" },
  { name: "Insta360", style: "font-semibold" },
  { name: "remarkable", style: "font-light lowercase tracking-[0.3em]" },
];
