// ── Single source of truth for all tracked brands ──
// Auto-generated from research. Product counts and activity are fetched
// dynamically at render time from Supabase via brandStats.ts.
// To add/remove brands, edit research sources and re-run scripts/merge-brands.mjs.

export interface Brand {
  name: string;
  domain: string;
  country: string | null;
  subcategory: string | null;
  description: string | null;
  // Dynamic fields — injected at render time via brandStats.enrichBrand()
  products: string;
  lastUpdate: string;
  latestChange: string;
}

export interface Vertical {
  id: string;
  label: string;
  brands: Brand[];
}

// Helper for defining brands concisely
function b(name: string, domain: string, country: string | null, subcategory: string | null, description: string | null): Brand {
  return {
    name,
    domain,
    country,
    subcategory,
    description,
    // Default placeholders — overwritten by enrichBrand() at render time
    products: "—",
    lastUpdate: "—",
    latestChange: "Tracking starts soon",
  };
}

export const VERTICALS: Vertical[] = [
  {
    id: "fashion",
    label: "Fashion",
    brands: [
      b("Allbirds", "allbirds.com", null, null, null),
      b("Away", "awaytravel.com", null, null, null),
      b("Chubbies", "chubbies.com", null, null, null),
      b("Cuts Clothing", "cutsclothing.com", null, null, null),
      b("Daniel Wellington", "danielwellington.com", null, null, null),
      b("Ekster", "ekster.com", null, null, null),
      b("Fashion Nova", "fashionnova.com", null, null, null),
      b("Greats", "greats.com", null, null, null),
      b("Kith", "kith.com", null, null, null),
      b("Knix", "knix.com", null, null, null),
      b("Koio", "koio.co", null, null, null),
      b("Lunya", "lunya.co", null, null, null),
      b("Mack Weldon", "mackweldon.com", null, null, null),
      b("Marine Layer", "marinelayer.com", null, null, null),
      b("Monos", "monos.com", null, null, null),
      b("OBEY Clothing", "obeyclothing.com", null, null, null),
      b("OddBalls", "myoddballs.com", null, null, null),
      b("Oliver Cabell", "olivercabell.com", null, null, null),
      b("Only NY", "onlyny.com", null, null, null),
      b("Outdoor Voices", "outdoorvoices.com", null, null, null),
      b("Quay Australia", "quayaustralia.com", null, null, null),
      b("Represent Clothing", "representclo.com", null, null, null),
      b("Rothy's", "rothys.com", null, null, null),
      b("Stance", "stance.com", null, null, null),
      b("Steve Madden", "stevemadden.com", null, null, null),
      b("Taylor Stitch", "taylorstitch.com", null, null, null),
      b("Tentree", "tentree.com", null, null, null),
      b("The Hundreds", "thehundreds.com", null, null, null),
      b("ThirdLove", "thirdlove.com", null, null, null),
      b("Thursday Boots", "thursdayboots.com", null, null, null),
      b("Todd Snyder", "toddsnyder.com", null, null, null),
      b("True Classic", "trueclassictees.com", null, null, null),
      b("Vessi", "vessi.com", null, null, null),
      b("Vincero", "vincerowatches.com", null, null, null),
      b("Aime Leon Dore", "aimeleondore.com", "US", "streetwear", "New York luxury streetwear and sportswear brand."),
      b("Albaray", "albaray.co.uk", "UK", "womenswear", "British womenswear brand offering responsibly made contemporary clothing."),
      b("Bo+Tee", "bo-tee.com", "UK", "activewear", "British activewear sub-brand of Oh Polly selling leggings, sports bras and crop tops."),
      b("Cole Buxton", "colebuxton.com", "UK", "contemporary sportswear", "Contemporary British sportswear brand making hoodies, tees and sweatpants designed and produced in Britain."),
      b("Community Clothing", "communityclothing.co.uk", "UK", "heritage basics", "Patrick Grant's social enterprise making affordable British-made staples."),
      b("Damson Madder", "damsonmadder.com", "UK", "womenswear", "London female-led label known for whimsical silhouettes and bold prints."),
      b("Finisterre", "finisterre.com", "UK", "outdoor/outerwear", "Cornwall-based cold-water surf and outdoor clothing brand with a sustainability focus."),
      b("HYPE", "justhype.co.uk", "UK", "streetwear", "British streetwear brand known for graphic prints and youth-focused collections."),
      b("Kestin", "kestin.co", "UK", "menswear", "Scottish menswear brand drawing on heritage workwear and contemporary menswear."),
      b("Kitri", "kitristudio.com", "UK", "womenswear", "London-based womenswear label founded by Haeni Kim, famed for statement printed dresses."),
      b("Lazy Oaf", "lazyoaf.com", "UK", "streetwear", "London independent streetwear label with playful, cartoon-inspired designs."),
      b("Lucy & Yak", "lucyandyak.com", "UK", "sustainable casualwear", "Independent UK brand famous for colourful organic cotton dungarees, jumpsuits and casualwear."),
      b("ME+EM", "meandem.com", "UK", "premium womenswear", "British premium womenswear brand founded by Clare Hornby offering elevated everyday pieces."),
      b("Never Fully Dressed", "neverfullydressed.com", "UK", "womenswear", "London-based womenswear label known for bold prints and wrap dresses."),
      b("Nobody's Child", "nobodyschild.com", "UK", "sustainable womenswear", "London sustainable women's fashion label producing limited runs using upcycled fabrics."),
      b("Oh Polly", "ohpolly.com", "UK", "womenswear", "Glasgow-based women's fashion brand specialising in figure-flattering dresses, tops and swimwear."),
      b("Olivia Rubin", "oliviarubinlondon.com", "UK", "womenswear", "London designer brand known for playful, colour-driven dresses."),
      b("Omnes", "omnes.com", "UK", "sustainable womenswear", "London sustainable womenswear label using recycled and deadstock materials."),
      b("Passenger Clothing", "passenger-clothing.com", "UK", "outdoor/lifestyle", "UK outdoor lifestyle brand selling travel-inspired clothing."),
      b("Pepper", "wearpepper.com", "US", "intimates", "Direct-to-consumer intimates brand tailored for women with smaller busts."),
      b("Percival", "percivalclo.com", "UK", "menswear", "British menswear label focused on modern takes on classic clothing."),
      b("Rixo", "rixo.co.uk", "UK", "womenswear", "London womenswear label known for hand-painted prints and vintage-inspired dresses."),
      b("Saturdays NYC", "saturdaysnyc.com", "US", "surf/casualwear", "New York surf-inspired menswear and lifestyle brand."),
      b("Sunspel", "sunspel.com", "UK", "heritage menswear", "Heritage British clothing brand known for luxury cotton tees, underwear and polos."),
      b("Wax London", "waxlondon.com", "UK", "menswear", "London menswear brand known for its patchwork Whiting overshirt and British-made clothing."),
      b("YMC", "youmustcreate.com", "UK", "contemporary clothing", "London contemporary menswear and womenswear brand (You Must Create)."),
      b("Alo Yoga", "aloyoga.com", null, null, null),
      b("UNTUCKit", "untuckit.com", null, null, null),
      b("Johnny Cupcakes", "johnnycupcakes.com", null, null, null),
      b("Birds of Condor", "birdsofcondor.com", null, null, null),
      b("NAADAM", "naadam.co", null, null, null),
      b("Komodo", "komodo.co.uk", null, null, null),
      b("Faherty", "fahertybrand.com", null, null, null),
      b("Tecovas", "tecovas.com", null, null, null),
      b("MATE the Label", "matethelabel.com", null, null, null),
      b("Corridor NYC", "corridornyc.com", null, null, null),
      b("Mott & Bow", "mottandbow.com", null, null, null),
      b("3sixteen", "3sixteen.com", null, null, null),
      b("Colorful Standard", "colorfulstandard.com", null, null, null),
      b("Organic Basics", "organicbasics.com", null, null, null),
      b("Noah", "noahny.com", null, null, null),
      b("Baukjen", "baukjen.com", null, null, null),
      b("Never Fully Dressed", "neverfullydressed.co.uk", null, null, null),
      b("Outerknown", "outerknown.com", null, null, null),
      b("SIRPLUS", "sirplus.co.uk", null, null, null),
      b("Ten Thousand", "tenthousand.cc", null, null, null),
      b("Richer Poorer", "richer-poorer.com", null, null, null),
      b("Negative Underwear", "negativeunderwear.com", null, null, null),
      b("SAXX", "saxxunderwear.com", null, null, null),
      b("Andie", "andieswim.com", null, null, null),
      b("Oner Active", "oneractive.com", null, null, null),
      b("NVGTN", "nvgtn.com", null, null, null),
      b("Reigning Champ", "reigningchamp.com", null, null, null),
      b("Left on Friday", "leftonfriday.com", null, null, null),
      b("Summersalt", "summersalt.com", null, null, null),
      b("Tommy John", "tommyjohn.com", null, null, null),
      b("Warp + Weft", "warpweftworld.com", null, null, null),
      b("Parade", "yourparade.com", null, null, null),
    ],
  },
  {
    id: "beauty",
    label: "Beauty & Wellness",
    brands: [
      b("Beauty Bakerie", "beautybakerie.com", null, null, null),
      b("Blueland", "blueland.com", null, null, null),
      b("Cocokind", "cocokind.com", null, null, null),
      b("ColourPop", "colourpop.com", null, null, null),
      b("Dr. Squatch", "drsquatch.com", null, null, null),
      b("Fenty Beauty", "fentybeauty.com", null, null, null),
      b("Function of Beauty", "functionofbeauty.com", null, null, null),
      b("Geologie", "geologie.com", null, null, null),
      b("Glossier", "glossier.com", null, null, null),
      b("Glow Recipe", "glowrecipe.com", null, null, null),
      b("Golde", "golde.co", null, null, null),
      b("Grove Collaborative", "grove.co", null, null, null),
      b("Harry's", "harrys.com", null, null, null),
      b("Iconic London", "iconiclondoninc.com", null, null, null),
      b("Jeffree Star Cosmetics", "jeffreestarcosmetics.com", null, null, null),
      b("Josie Maran", "josiemaran.com", null, null, null),
      b("Kopari", "koparibeauty.com", null, null, null),
      b("Kylie Cosmetics", "kyliecosmetics.com", null, null, null),
      b("Lumin", "luminskin.com", null, null, null),
      b("Moon Juice", "moonjuice.com", null, null, null),
      b("Native", "nativecos.com", null, null, null),
      b("Oars + Alps", "oarsandalps.com", null, null, null),
      b("Olaplex", "olaplex.com", null, null, null),
      b("Olly", "olly.com", null, null, null),
      b("Ouai", "theouai.com", null, null, null),
      b("Pixi Beauty", "pixibeauty.com", null, null, null),
      b("Quip", "getquip.com", null, null, null),
      b("Rare Beauty", "rarebeauty.com", null, null, null),
      b("Ritual", "ritual.com", null, null, null),
      b("Saje Natural Wellness", "saje.com", null, null, null),
      b("Snow Teeth Whitening", "trysnow.com", null, null, null),
      b("Stila Cosmetics", "stilacosmetics.com", null, null, null),
      b("Summer Fridays", "summerfridays.com", null, null, null),
      b("The Beauty Chef", "thebeautychef.com", null, null, null),
      b("The Honey Pot", "thehoneypot.co", null, null, null),
      b("Tropic Skincare", "tropicskincare.com", null, null, null),
      b("Tru Earth", "tru.earth", null, null, null),
      b("Vital Proteins", "vitalproteins.com", null, null, null),
      b("Vitruvi", "vitruvi.com", null, null, null),
      b("Bare Biology", "barebiology.com", "UK", "supplements", "British premium omega-3 fish oil supplements brand."),
      b("Beauty Pie", "beautypie.com", "UK", "cosmetics club", "London beauty buyers' club offering luxury beauty products at cost to members."),
      b("Bloom & Blossom", "bloomandblossom.com", "UK", "wellness/skincare", "British wellness and skincare brand known for bath and body products."),
      b("Bouclème", "boucleme.co.uk", "UK", "haircare", "British haircare brand focused on products for curly hair."),
      b("Byoma", "byoma.com", "UK", "barrier skincare", "UK-founded affordable barrier-health skincare brand."),
      b("Dr. Sam's", "drsambunting.com", "UK", "dermatologist skincare", "London dermatologist-founded skincare brand by Dr Sam Bunting."),
      b("Earl of East", "earlofeast.com", "UK", "home fragrance", "London candle and home fragrance brand."),
      b("Elemis", "elemis.myshopify.com", "UK", "skincare", "Luxury British anti-ageing skincare brand."),
      b("Evolve Beauty", "evolvebeauty.co.uk", "UK", "natural skincare", "Hertfordshire artisan natural, vegan, cruelty-free beauty brand."),
      b("Facetheory", "facetheory.com", "UK", "accessible skincare", "Sheffield-based vegan cruelty-free skincare brand at accessible prices."),
      b("Form Nutrition", "formnutrition.com", "UK", "plant protein", "London plant-based protein and supplements brand."),
      b("Haeckels", "haeckels.co.uk", "UK", "natural skincare", "Margate-based natural skincare brand using locally foraged seaweed and botanicals."),
      b("Illamasqua", "illamasqua.com", "UK", "makeup", "British cult makeup brand with bold and artistic colour palettes."),
      b("Innermost", "liveinnermost.com", "UK", "supplements", "UK premium supplements and nutrition brand."),
      b("Medik8", "medik8.com", "UK", "pro skincare", "British professional skincare brand built on vitamin C/A/SPF philosophy."),
      b("Neom Organics", "neomorganics.com", "UK", "wellbeing fragrance", "Yorkshire-based wellbeing brand making natural candles and bath products."),
      b("Noughty Haircare", "lovenoughty.co.uk", "UK", "haircare", "UK vegan haircare brand powered by up to 97% natural ingredients."),
      b("Pai Skincare", "paiskincare.com", "UK", "sensitive skincare", "British organic skincare brand focused on sensitive skin."),
      b("Revolution Beauty", "revolutionbeauty.com", "UK", "mass cosmetics", "UK affordable cosmetics brand."),
      b("Ruby Hammer", "rubyhammer.com", "UK", "makeup tools", "UK makeup brand from celebrity makeup artist Ruby Hammer."),
      b("Skin + Me", "skinandme.com", "UK", "personalised skincare", "UK personalised prescription skincare brand using a quiz-first buying flow."),
      b("Skin Rocks", "skinrocks.com", "UK", "skincare", "Caroline Hirons' London-based skincare brand."),
      b("UpCircle Beauty", "upcirclebeauty.com", "UK", "sustainable skincare", "UK skincare brand making products from upcycled ingredients like coffee grounds."),
      b("Votary", "votary.co.uk", "UK", "natural skincare", "British skincare brand focused on plant-oil based facial oils and cleansers."),
      b("Wild", "wearewild.myshopify.com", "UK", "refillable personal care", "UK refillable natural deodorant and personal care brand."),
      b("Faith In Nature", "faithinnature.co.uk", null, null, null),
      b("ILIA Beauty", "iliabeauty.com", null, null, null),
      b("OSEA Malibu", "oseamalibu.com", null, null, null),
      b("Jones Road", "jonesroadbeauty.com", null, null, null),
      b("Kosas", "kosas.com", null, null, null),
      b("beautyblender", "beautyblender.com", null, null, null),
      b("Salt & Stone", "saltandstone.com", null, null, null),
      b("Merit", "meritbeauty.com", null, null, null),
      b("Westman Atelier", "westman-atelier.com", null, null, null),
      b("Fussy", "getfussy.com", null, null, null),
      b("The INKEY List", "theinkeylist.com", null, null, null),
      b("Farmacy", "farmacybeauty.com", null, null, null),
      b("Nécessaire", "necessaire.com", null, null, null),
      b("VEGAMOUR", "vegamour.com", null, null, null),
      b("Versed", "versedskin.com", null, null, null),
      b("Gisou", "gisou.com", null, null, null),
      b("Makeup By Mario", "makeupbymario.com", null, null, null),
      b("REFY", "refy.com", null, null, null),
      b("Tower 28", "tower28beauty.com", null, null, null),
      b("Saie", "saiehello.com", null, null, null),
      b("Act+Acre", "actandacre.com", null, null, null),
      b("Hero Cosmetics", "herocosmetics.us", null, null, null),
      b("K18", "k18hair.com", null, null, null),
      b("Hairstory", "hairstory.com", null, null, null),
      b("Naturium", "naturium.com", null, null, null),
      b("JVN", "jvnhair.com", null, null, null),
      b("Ceremonia", "ceremonia.com", null, null, null),
      b("Crown Affair", "crownaffair.com", null, null, null),
      b("HiSmile", "hismileteeth.com", null, null, null),
      b("Starface", "starface.world", null, null, null),
      b("War Paint", "warpaintformen.com", null, null, null),
      b("KraveBeauty", "kravebeauty.com", null, null, null),
    ],
  },
  {
    id: "home",
    label: "Home & Garden",
    brands: [
      b("Aer", "aersf.com", null, null, null),
      b("Big Agnes", "bigagnes.com", null, null, null),
      b("Boll & Branch", "bollandbranch.com", null, null, null),
      b("Breeo", "breeo.co", null, null, null),
      b("Brooklinen", "brooklinen.com", null, null, null),
      b("Casper", "casper.com", null, null, null),
      b("Chrome Industries", "chromeindustries.com", null, null, null),
      b("Corkcicle", "corkcicle.com", null, null, null),
      b("Fast Growing Trees", "fastgrowingtrees.com", null, null, null),
      b("Floyd", "floydhome.com", null, null, null),
      b("Gozney", "gozney.com", null, null, null),
      b("Incase", "incase.com", null, null, null),
      b("Maiden Home", "maidenhome.com", null, null, null),
      b("Minaal", "minaal.com", null, null, null),
      b("Nomatic", "nomatic.com", null, null, null),
      b("Ooni", "ooni.com", null, null, null),
      b("Outer", "liveouter.com", null, null, null),
      b("Parachute Home", "parachutehome.com", null, null, null),
      b("Peak Design", "peakdesign.com", null, null, null),
      b("Rumpl", "rumpl.com", null, null, null),
      b("S'well", "swell.com", null, null, null),
      b("Sandmarc", "sandmarc.com", null, null, null),
      b("Sea to Summit", "seatosummit.com", null, null, null),
      b("Snow Peak", "snowpeak.com", null, null, null),
      b("Society6", "society6.com", null, null, null),
      b("Stanley 1913", "stanley1913.com", null, null, null),
      b("Timbuk2", "timbuk2.com", null, null, null),
      b("Tortuga", "tortugabackpacks.com", null, null, null),
      b("Waterfield Designs", "sfbags.com", null, null, null),
      b("Aery Living", "aeryliving.com", "UK", "home fragrance", "UK aromatherapy candles, diffusers and bath brand."),
      b("Bert & May", "bertandmay.com", "UK", "decor", "UK encaustic tiles and interiors brand."),
      b("Case Furniture", "casefurniture.com", "UK", "furniture", "British contemporary designer furniture manufacturer."),
      b("Danetti", "danetti.com", "UK", "furniture", "UK contemporary furniture brand based in Berkshire."),
      b("Darcey's Candles", "darceyscandles.co.uk", "UK", "home fragrance", "Scottish luxury handcrafted soy wax candles and wax melts."),
      b("Emma Bridgewater", "emmabridgewater.co.uk", "UK", "tableware", "Quintessentially British pottery and tableware brand from Stoke-on-Trent."),
      b("Ettinger", "ettinger.co.uk", "UK", "homeware", "British luxury leather goods and home accessories brand."),
      b("eve Sleep", "evesleep.co.uk", "UK", "bedding", "UK mattress and bedding DTC brand."),
      b("Gold Moss", "goldmoss.co.uk", "UK", "home fragrance", "Scottish hand-poured soy candle and reed diffuser brand."),
      b("Grove Bags", "grove.com", "UK", "garden", "UK garden tools and accessories."),
      b("Houseof", "houseof.com", "UK", "lighting", "UK contemporary lighting and homeware brand."),
      b("Houseplant", "houseplant.co.uk", "UK", "plants", "UK online houseplant retailer."),
      b("Labour and Wait", "labourandwait.co.uk", "UK", "homeware", "London traditional timeless homeware and hardware shop."),
      b("LINLEY", "davidlinley.com", "UK", "furniture", "British luxury bespoke furniture and interior design brand."),
      b("Niwaki", "niwaki.com", "UK", "garden", "UK Japanese garden tools and kitchenware brand."),
      b("Piglet in Bed", "pigletinbed.com", "UK", "bedding", "UK linen bedding and loungewear brand."),
      b("Robert Welch", "robertwelch.com", "UK", "kitchenware", "British family-run brand for designer cutlery and kitchen tools."),
      b("Rockett St George", "rockettstgeorge.co.uk", "UK", "decor", "UK eclectic homeware and interiors retailer."),
      b("Simba Sleep", "simbasleep.com", "UK", "bedding", "British hybrid mattress and bedding DTC brand founded in 2015."),
      b("Soho Home", "sohohome.com", "UK", "homeware", "Soho House-owned UK homeware and furniture brand."),
      b("Sophie Allport", "sophieallport.com", "UK", "homeware", "UK homeware brand known for illustrated fine-bone china, textiles and kitchenware."),
      b("Tala", "tala.co.uk", "UK", "lighting", "UK sustainable LED lighting brand."),
      b("TOAST", "toa.st", "UK", "homeware", "UK lifestyle brand selling clothing, homeware and handmade tableware."),
      b("Whitehall Garden Centres", "whitehallgardencentre.co.uk", "UK", "garden", "Family-run UK garden centre selling plants, furniture and decor."),
      b("Coyuchi", "coyuchi.com", null, null, null),
      b("Public Goods", "publicgoods.com", null, null, null),
      b("Our Place", "fromourplace.com", null, null, null),
      b("Snowe", "snowehome.com", null, null, null),
      b("Poly & Bark", "polyandbark.com", null, null, null),
      b("Lulu and Georgia", "luluandgeorgia.com", null, null, null),
      b("Avocado", "avocadogreenmattress.com", null, null, null),
      b("Sarah Raven", "sarahraven.com", null, null, null),
      b("Sabai", "sabai.design", null, null, null),
      b("Cozy Earth", "cozyearth.com", null, null, null),
      b("Branch", "branchfurniture.com", null, null, null),
      b("Thuma", "thuma.co", null, null, null),
      b("Schoolhouse", "schoolhouse.com", null, null, null),
      b("Tuft & Needle", "tuftandneedle.com", null, null, null),
      b("Sijo", "sijohome.com", null, null, null),
      b("ettitude", "ettitude.com", null, null, null),
      b("Bearaby", "bearaby.com", null, null, null),
      b("P.F. Candle Co.", "pfcandleco.com", null, null, null),
      b("Smithey", "smithey.com", null, null, null),
      b("Otherland", "otherland.com", null, null, null),
      b("W&P", "wandpdesign.com", null, null, null),
    ],
  },
  {
    id: "food",
    label: "Food & Beverage",
    brands: [
      b("Beekeeper's Naturals", "beekeepersnaturals.com", null, null, null),
      b("ButcherBox", "butcherbox.com", null, null, null),
      b("Chemex", "chemexcoffeemaker.com", null, null, null),
      b("Chomps", "chomps.com", null, null, null),
      b("Counter Culture", "counterculturecoffee.com", null, null, null),
      b("Daily Harvest", "daily-harvest.com", null, null, null),
      b("Death Wish Coffee", "deathwishcoffee.com", null, null, null),
      b("Fellow", "fellowproducts.com", null, null, null),
      b("Fly by Jing", "flybyjing.com", null, null, null),
      b("Four Sigmatic", "foursigmatic.com", null, null, null),
      b("Ghia", "drinkghia.com", null, null, null),
      b("Great Jones", "greatjonesgoods.com", null, null, null),
      b("Heatonist", "heatonist.com", null, null, null),
      b("HexClad", "hexclad.com", null, null, null),
      b("Laird Superfood", "lairdsuperfood.com", null, null, null),
      b("Liquid Death", "liquiddeath.com", null, null, null),
      b("Magic Spoon", "magicspoon.com", null, null, null),
      b("Material Kitchen", "materialkitchen.com", null, null, null),
      b("Milk Bar", "milkbarstore.com", null, null, null),
      b("Misen", "misen.com", null, null, null),
      b("MUDWTR", "mudwtr.com", null, null, null),
      b("Olipop", "drinkolipop.com", null, null, null),
      b("Partake Foods", "partakefoods.com", null, null, null),
      b("Poppi", "drinkpoppi.com", null, null, null),
      b("Red Bull Shop", "redbullshopus.com", null, null, null),
      b("Snake River Farms", "snakeriverfarms.com", null, null, null),
      b("Soylent", "soylent.com", null, null, null),
      b("Splendid Spoon", "splendidspoon.com", null, null, null),
      b("Stumptown Coffee", "stumptowncoffee.com", null, null, null),
      b("Verve Coffee", "vervecoffee.com", null, null, null),
      b("allplants", "allplants.com", "UK", "meal kits", "UK plant-based frozen ready-meal subscription service."),
      b("Beavertown Brewery", "beavertownbrewery.co.uk", "UK", "beverages", "London craft brewery selling beers, seltzers and merch direct to consumer."),
      b("Bird & Blend Tea Co.", "birdandblendtea.com", "UK", "tea", "UK blended loose leaf tea company with creative flavour blends."),
      b("Bluebird Tea Co", "bluebirdteaco.com", "UK", "tea", "UK loose leaf tea brand (part of Bird & Blend group)."),
      b("Candy Kittens", "candykittens.co.uk", "UK", "snacks", "UK gourmet vegan gummy sweets brand."),
      b("ChicP", "chicp.co.uk", "UK", "snacks", "UK sustainable hummus and dips brand."),
      b("DASH Water", "dash-water.com", "UK", "beverages", "UK sparkling water infused with wonky fruit."),
      b("Days Brewing", "daysbrewing.com", "UK", "beverages", "UK alcohol-free craft beer brand."),
      b("Doisy & Dam", "doisyanddam.com", "UK", "snacks", "UK ethical chocolate brand with superfood-infused bars."),
      b("Exhale Coffee", "exhalecoffee.com", "UK", "coffee", "UK high-antioxidant functional coffee brand."),
      b("Grind", "grind.co.uk", "UK", "coffee", "London-born coffee brand selling compostable coffee pods, beans and subscriptions."),
      b("IMPOSSIBREW", "impossibrew.co.uk", "UK", "beverages", "UK functional alcohol-free beer with a proprietary social blend."),
      b("JING Tea", "jingtea.com", "UK", "tea", "UK premium single-origin loose leaf tea and teaware."),
      b("Mallow & Marsh", "mallowandmarsh.com", "UK", "snacks", "UK marshmallow snacks and treats brand."),
      b("Minor Figures", "minorfigures.com", "UK", "beverages", "UK oat milk and cold-brew coffee brand."),
      b("Pasta Evangelists", "pastaevangelists.com", "UK", "meal kits", "UK luxury fresh pasta meal-kit delivery service."),
      b("Pentire Drinks", "pentiredrinks.com", "UK", "beverages", "Cornish non-alcoholic botanical aperitif distilled from coastal plants."),
      b("Pinter", "pinter.com", "UK", "beverages", "UK make-your-own craft beer appliance and ingredient kits."),
      b("Pip & Nut", "pipandnut.com", "UK", "snacks", "UK nut butter brand selling almond, peanut and cashew butters plus snack packs."),
      b("Press London", "press-london.com", "UK", "beverages", "Cold-pressed juice and cleanse programme brand based in London."),
      b("Rave Coffee", "ravecoffee.co.uk", "UK", "coffee", "Cotswolds-based specialty coffee roaster with subscription."),
      b("Seedlip", "us.seedlipdrinks.com", "UK", "beverages", "British non-alcoholic distilled spirit brand."),
      b("Sipful", "sipful.co.uk", "UK", "beverages", "UK functional wellness drinks brand."),
      b("Square Mile Coffee Roasters", "shop.squaremilecoffee.com", "UK", "coffee", "London specialty coffee roaster founded by James Hoffmann."),
      b("Three Spirit", "threespiritdrinks.com", "UK", "beverages", "UK non-alcoholic functional drinks with adaptogens and nootropics."),
      b("Athletic Brewing", "athleticbrewing.com", null, null, null),
      b("Graza", "graza.co", null, null, null),
      b("Hydrant", "drinkhydrant.com", null, null, null),
      b("Tony’s Chocolonely", "tonyschocolonely.com", null, null, null),
      b("BREZ", "drinkbrez.com", null, null, null),
      b("HOP WTR", "hopwtr.com", null, null, null),
      b("BLK & Bold", "blkandbold.com", null, null, null),
      b("De Soi", "drinkdesoi.com", null, null, null),
      b("Kin Euphorics", "kineuphorics.com", null, null, null),
      b("Aura Bora", "aurabora.com", null, null, null),
      b("Sanzo", "drinksanzo.com", null, null, null),
      b("Trade Coffee", "drinktrade.com", null, null, null),
      b("Onyx Coffee Lab", "onyxcoffeelab.com", null, null, null),
      b("Bones Coffee", "bonescoffee.com", null, null, null),
      b("Wandering Bear", "wanderingbearcoffee.com", null, null, null),
      b("LesserEvil", "lesserevil.com", null, null, null),
      b("Mid-Day Squares", "middaysquares.com", null, null, null),
    ],
  },
  {
    id: "electronics",
    label: "Electronics & Tech",
    brands: [
      b("Arduino", "store.arduino.cc", null, null, null),
      b("Boox", "shop.boox.com", null, null, null),
      b("Elegoo", "elegoo.com", null, null, null),
      b("Glorious Gaming", "gloriousgaming.com", null, null, null),
      b("Jackery", "jackery.com", null, null, null),
      b("Keychron", "keychron.com", null, null, null),
      b("Loop Earplugs", "loopearplugs.com", null, null, null),
      b("Master & Dynamic", "masterdynamic.com", null, null, null),
      b("Native Union", "nativeunion.com", null, null, null),
      b("NZXT", "nzxt.com", null, null, null),
      b("Paperlike", "paperlike.com", null, null, null),
      b("Pela Case", "pelacase.com", null, null, null),
      b("Ridge Wallet", "ridgewallet.com", null, null, null),
      b("Secretlab", "secretlab.co", null, null, null),
      b("Shokz", "shokz.com", null, null, null),
      b("Supernote", "supernote.com", null, null, null),
      b("Twelve South", "twelvesouth.com", null, null, null),
      b("Bookman", "bookman.se", "EU", "urban cycling lights", "Swedish minimalist cycling lights and visibility accessories sold into UK."),
      b("Cabbage Tech / Buddyphones", "onanoff.com", "UK", "kids headphones", "European/UK distributed kids' volume-limited headphones (UK-facing storefront)."),
      b("Cambridge Audio", "cambridgeaudio.com", "UK", "hi-fi electronics", "London-based hi-fi electronics and speaker manufacturer."),
      b("Firebox", "firebox.myshopify.com", "UK", "gadgets / gifts", "UK gadget and gift retailer."),
      b("Flare Audio", "flareaudio.com", "UK", "earphones / hearing protection", "UK in-ear monitor and acoustic ear plug brand."),
      b("Grovemade EU/UK", "grovemade.com", "US", "desk accessories", "Premium wood desk accessories (US brand with UK shipping)."),
      b("Hiive", "hiive.co.uk", "UK", "smart home", "UK smart home heating and energy management brand."),
      b("I Want One Of Those", "iwantoneofthose.com", "UK", "gadgets", "UK heritage gadget retailer."),
      b("Juice", "juice.co.uk", "UK", "charging / power banks", "UK charging accessories brand selling cables, chargers and power banks."),
      b("LIFX UK", "lifx.co.uk", "UK", "smart lighting", "UK storefront for smart lighting brand."),
      b("Lumie", "lumie.com", "UK", "wake-up / SAD lamps", "UK inventor of the wake-up light and bodyclock, selling SAD and wellbeing lamps."),
      b("Mous", "mous.co", "UK", "phone cases / accessories", "London-based premium protective phone case and wireless charging accessory brand."),
      b("Oakywood UK", "oakywood.shop", "EU", "desk accessories", "Wooden desk and tech accessories brand serving UK/EU customers."),
      b("Pimoroni", "shop.pimoroni.com", "UK", "maker / electronics", "Sheffield-based Raspberry Pi and maker electronics retailer."),
      b("Ruark Audio", "shop.ruarkaudio.com", "UK", "hi-fi audio", "Essex-based premium radio and hi-fi brand."),
      b("Tech21", "tech21.com", "UK", "phone cases / screen protection", "UK protective tech accessories brand known for FlexShock case technology."),
      b("The Pi Hut", "thepihut.com", "UK", "maker / electronics", "UK Raspberry Pi and electronics components retailer."),
      b("TORRO", "torro.co.uk", "UK", "leather tech accessories", "Newcastle-based premium leather phone cases, wallets and tech accessories."),
      b("Urbanista", "urbanista.com", "EU", "headphones", "Stockholm-based lifestyle audio brand selling to UK consumers."),
      b("Vanguard UK", "vanguardworld.co.uk", "UK", "camera / optics accessories", "UK storefront for camera bags, tripods and optics."),
      b("MOFT", "moft.us", null, null, null),
      b("Glorious", "pcgamingrace.com", null, null, null),
      b("Orbitkey", "orbitkey.com", null, null, null),
      b("PITAKA", "ipitaka.com", null, null, null),
      b("Courant", "staycourant.com", null, null, null),
      b("UGREEN", "ugreen.com", null, null, null),
      b("Audeze", "audeze.com", null, null, null),
      b("Sharge", "sharge.com", null, null, null),
      b("Campfire Audio", "campfireaudio.com", null, null, null),
    ],
  },
  {
    id: "sports",
    label: "Sports & Outdoors",
    brands: [
      b("Black Diamond", "blackdiamondequipment.com", null, null, null),
      b("Cotopaxi", "cotopaxi.com", null, null, null),
      b("ENO", "eaglesnestoutfittersinc.com", null, null, null),
      b("Filson", "filson.com", null, null, null),
      b("GSI Outdoors", "gsioutdoors.com", null, null, null),
      b("Gymshark", "gymshark.com", null, null, null),
      b("Kammok", "kammok.com", null, null, null),
      b("Kifaru", "kifaru.net", null, null, null),
      b("Kuiu", "kuiu.com", null, null, null),
      b("Simms Fishing", "simmsfishing.com", null, null, null),
      b("Stone Glacier", "stoneglacier.com", null, null, null),
      b("Topo Designs", "topodesigns.com", null, null, null),
      b("Vertx", "vertx.com", null, null, null),
      b("Alpkit", "alpkit.com", "UK", "outdoor gear", "Nottinghamshire-based outdoor, camping and trail running equipment brand."),
      b("Ashmei", "ashmei.com", "UK", "running & cycling apparel", "British premium merino-based running and cycling kit brand."),
      b("Hunt Bike Wheels", "huntbikewheels.com", "UK", "cycling wheels", "UK direct-to-consumer cycling wheelset brand."),
      b("Le Col", "lecol.cc", "UK", "cycling apparel", "British premium cycling kit brand co-founded by Yanto Barker."),
      b("Muc-Off", "muc-off.com", "UK", "bike cleaning", "Poole-based bike cleaning, lube and care product brand."),
      b("Parcours", "parcours.cc", "UK", "cycling wheels", "UK direct-to-consumer carbon wheel brand for road and TT."),
      b("Presca Endurance / Proviz", "provizsports.com", "UK", "hi-viz sports apparel", "UK high-visibility running/cycling/outdoor apparel brand."),
      b("Presca Teamwear", "prescateamwear.com", "UK", "sustainable sportswear", "UK sustainable recycled-polyester sportswear and running apparel brand."),
      b("Restrap", "restrap.com", "UK", "cycling bags", "Yorkshire-based bikepacking and cycling accessories brand."),
      b("Runderwear", "runderwear.co.uk", "UK", "running base layers", "UK chafe-free running underwear and base-layer brand."),
      b("Snugpak", "snugpak.com", "UK", "sleeping bags / camping", "UK manufacturer of sleeping bags, jackets and tactical camping gear."),
      b("Spatzwear", "spatzwear.com", "UK", "cycling overshoes", "UK cycling overshoe and accessory brand."),
      b("Sungod", "sungod.co", "UK", "sports eyewear", "UK performance sunglasses and goggles brand for cycling, running and snowsports."),
      b("Trakke", "trakke.co.uk", "UK", "bags / outdoor", "Glasgow-based handmade waxed canvas bag and outdoor gear maker."),
      b("Veloforte", "veloforte.com", "UK", "endurance nutrition", "UK natural endurance nutrition bars, chews and hydration mixes."),
      b("Gymreapers", "gymreapers.com", null, null, null),
      b("Bear Bottom", "bearbottomclothing.com", null, null, null),
      b("Janji", "janji.com", null, null, null),
      b("Ombraz", "ombraz.com", null, null, null),
      b("Ciele", "cieleathletics.com", null, null, null),
      b("Born Primitive", "bornprimitive.com", null, null, null),
      b("District Vision", "districtvision.com", null, null, null),
      b("Roark", "roark.com", null, null, null),
      b("Satisfy", "satisfyrunning.com", null, null, null),
      b("Café du Cycliste", "cafeducycliste.com", null, null, null),
      b("Bandit Running", "banditrunning.com", null, null, null),
      b("Florence Marine X", "florencemarinex.com", null, null, null),
      b("PATH Projects", "pathprojects.com", null, null, null),
      b("Sundried", "sundried.com", null, null, null),
      b("Universal Colours", "universalcolours.com", null, null, null),
      b("Gossamer Gear", "gossamergear.com", null, null, null),
      b("Oiselle", "oiselle.com", null, null, null),
      b("Matador", "matadorequipment.com", null, null, null),
      b("Manduka", "manduka.com", null, null, null),
      b("Pearson1860", "pearson1860.com", null, null, null),
    ],
  },
  {
    id: "kids",
    label: "Kids & Baby",
    brands: [
      b("Baby Brezza", "babybrezza.com", null, null, null),
      b("Boba", "boba.com", null, null, null),
      b("Boppy", "boppy.com", null, null, null),
      b("Copper Pearl", "copperpearl.com", null, null, null),
      b("Earth Mama", "earthmamaorganics.com", null, null, null),
      b("Elvie", "elvie.com", null, null, null),
      b("Gathre", "gathre.com", null, null, null),
      b("Haakaa", "haakaa.com", null, null, null),
      b("Jamie Kay", "jamiekay.com", null, null, null),
      b("Lalo", "meetlalo.com", null, null, null),
      b("LILLEbaby", "lillebaby.com", null, null, null),
      b("Little Sleepies", "littlesleepies.com", null, null, null),
      b("Little Unicorn", "littleunicorn.com", null, null, null),
      b("Mushie", "mushie.com", null, null, null),
      b("Mustela", "mustelausa.com", null, null, null),
      b("Nanit", "nanit.com", null, null, null),
      b("Nugget", "nuggetcomfort.com", null, null, null),
      b("Owlet", "owletcare.com", null, null, null),
      b("Primary", "primary.com", null, null, null),
      b("Quincy Mae", "quincymae.com", null, null, null),
      b("Tubby Todd", "tubbytodd.com", null, null, null),
      b("Tula", "babytula.com", null, null, null),
      b("Willow", "onewillow.com", null, null, null),
      b("Babipur", "babipur.co.uk", "UK", "kids retail", "UK ethical baby and children's product retailer."),
      b("Blue Brontide", "bluebrontide.com", "UK", "toys", "UK eco-friendly handmade wooden toys and tableware for kids."),
      b("Bobo Choses UK", "bobochoses.com", "EU", "kids clothing", "Spanish kids clothing brand with strong UK presence."),
      b("Ergobaby UK", "ergobaby.co.uk", "UK", "baby gear", "UK baby carrier brand site."),
      b("Frugi", "welovefrugi.com", "UK", "kids clothing", "UK organic cotton children and baby clothing brand."),
      b("Kidly", "kidly.co.uk", "UK", "kids retail", "UK curated children's brand retailer for clothes, toys and nursery."),
      b("KIT & KIN", "kitandkin.com", "UK", "baby care", "UK eco nappies and baby skincare brand co-founded by Emma Bunton."),
      b("Little Green Radicals", "littlegreenradicals.co.uk", "UK", "kids clothing", "UK fair trade organic children's clothing brand."),
      b("Mamas & Papas", "mamasandpapas.com", "UK", "baby gear", "UK nursery, pushchair and baby gear retailer."),
      b("MORI", "babymori.com", "UK", "baby clothing", "UK organic cotton and bamboo baby sleepwear and daywear."),
      b("My 1st Years", "my1styears.com", "UK", "baby gifts", "UK personalised baby gifts and clothing."),
      b("Orange Tree Toys", "orangetreetoys.com", "UK", "toys", "Cotswolds-based British wooden toy and nursery decor brand."),
      b("Pine + Pear co", "pineandpear.co.uk", "UK", "nursery", "UK nursery decor, wooden toys and baby essentials."),
      b("Scandiborn", "scandiborn.co.uk", "UK", "nursery", "UK Scandinavian-inspired kids clothing, toys and nursery decor."),
      b("Seraphine", "seraphine.com", "UK", "maternity", "UK premium maternity wear brand."),
      b("Soren's House", "sorenshouse.co.uk", "UK", "toys", "UK natural and sustainable wooden toys for babies and kids."),
      b("Tender Leaf Toys", "tenderleaftoys.com", "UK", "toys", "UK designed sustainable wooden toy brand."),
      b("The Bonnie Mob", "thebonniemob.com", "UK", "baby clothing", "UK sustainable kids and baby clothing brand from Brighton."),
      b("The Little Green Sheep", "thelittlegreensheep.co.uk", "UK", "nursery", "UK organic baby nursery bedding and mattress brand."),
      b("The Thrifty Stork", "thethriftystork.co.uk", "UK", "kids retail", "UK independent ethical organic baby and kids clothing retailer."),
      b("Turtledove London", "turtledovelondon.com", "UK", "baby clothing", "UK organic and sustainable baby and kids clothing."),
      b("Kyte Baby", "kytebaby.com", null, null, null),
      b("Maisonette", "maisonette.com", null, null, null),
      b("Lalo", "lalo.com", null, null, null),
      b("Snüz", "snuz.co.uk", null, null, null),
      b("Solly Baby", "sollybaby.com", null, null, null),
      b("Magnetic Me", "magneticme.com", null, null, null),
      b("Tiny Cottons", "tinycottons.com", null, null, null),
      b("Tutti Bambini", "tuttibambini.com", null, null, null),
      b("Kickee Pants", "kickeepants.com", null, null, null),
      b("Lalabu", "lalabu.com", null, null, null),
      b("Colored Organics", "coloredorganics.com", null, null, null),
    ],
  },
  {
    id: "pets",
    label: "Pets",
    brands: [
      b("A Pup Above", "apupabove.com", null, null, null),
      b("Diggs", "diggs.pet", null, null, null),
      b("Found My Animal", "foundmyanimal.com", null, null, null),
      b("Harry Barker", "harrybarker.com", null, null, null),
      b("Impact Dog Crates", "impactdogcrates.com", null, null, null),
      b("Jinx", "thinkjinx.com", null, null, null),
      b("Maxbone", "maxbone.com", null, null, null),
      b("Open Farm", "openfarmpet.com", null, null, null),
      b("P.L.A.Y.", "petplay.com", null, null, null),
      b("Rifle Paper Co Pets", "riflepaperco.com", null, null, null),
      b("Ruffwear", "ruffwear.com", null, null, null),
      b("Sleepypod", "sleepypod.com", null, null, null),
      b("Stella & Chewy's", "stellaandchewys.com", null, null, null),
      b("The Foggy Dog", "thefoggydog.com", null, null, null),
      b("Tuft + Paw", "tuftandpaw.com", null, null, null),
      b("Up Country", "upcountryinc.com", null, null, null),
      b("West Paw", "westpaw.com", null, null, null),
      b("Wild One", "wildone.com", null, null, null),
      b("Wolfgang Man & Beast", "wolfgangusa.com", null, null, null),
      b("Zee.Dog", "zeedog.com", null, null, null),
      b("Ziwi Peak", "ziwipets.com", null, null, null),
      b("Barking Heads", "barkingheads.co.uk", "UK", "pet food", "UK natural dog and cat food brand."),
      b("Bella & Duke", "bellaandduke.com", "UK", "raw pet food", "UK raw food subscription for dogs and cats."),
      b("Butternut Box", "shop.butternutbox.com", "UK", "dog food", "UK fresh dog food subscription service."),
      b("Edgard & Cooper", "us.edgardcooper.com", "EU", "pet food", "Belgian/UK natural dog and cat food brand."),
      b("Forthglade", "forthglade.com", "UK", "dog food", "UK natural wet dog food and treats brand."),
      b("Hiro + Wolf", "hiroandwolf.com", "UK", "accessories", "UK East London dog collars, leads and accessories with global prints."),
      b("Holland Cooper Dog", "hollandscountryclothing.co.uk", "UK", "accessories", "UK tweed dog collars, coats and country accessories."),
      b("Katkin", "katkin.com", "UK", "cat food", "UK fresh cat food delivery service using human-grade meat."),
      b("Kip & Twiggy's", "kipandtwiggys.com", "UK", "dog food", "UK natural dog treats."),
      b("Lily's Kitchen", "lilyskitchen.co.uk", "UK", "pet food", "UK natural pet food brand."),
      b("LISH London", "lishlondon.com", "UK", "accessories", "UK luxury canine couture brand - sweaters, collars, beds."),
      b("Mutts & Hounds", "muttsandhounds.co.uk", "UK", "accessories", "UK luxury dog beds, collars, leads and carriers made in Britain."),
      b("Natural Instinct", "naturalinstinct.com", "UK", "raw pet food", "UK raw pet food brand."),
      b("Pets Purest", "petspurest.com", "UK", "supplements", "UK natural pet supplements and treats."),
      b("Pooch & Mutt", "poochandmutt.com", "UK", "dog food", "UK natural dog food, treats and supplements brand."),
      b("Poppy's Picnic", "poppyspicnic.co.uk", "UK", "dog food", "UK raw dog food and complete meal brand."),
      b("Scrumbles", "scrumbles.co.uk", "UK", "pet food", "UK gut-friendly dog and cat food brand."),
      b("Tails.com", "tails.com", "UK", "dog food", "UK tailored dry dog food subscription."),
      b("Teddy Maximus", "teddymaximus.com", "UK", "accessories", "British-style personalised dog accessories including harnesses and coats."),
      b("Tribal Pet Foods", "tribalpetfoods.co.uk", "UK", "dog food", "UK cold-pressed dog food brand."),
      b("YuMove", "yumove.co.uk", "UK", "supplements", "UK joint supplement brand for dogs and cats."),
      b("Pupford", "pupford.com", null, null, null),
      b("Fable Pets", "fablepets.com", null, null, null),
      b("Waggo", "waggo.com", null, null, null),
      b("Wild Earth", "wildearth.com", null, null, null),
      b("Lords & Labradors", "lordsandlabradors.co.uk", null, null, null),
      b("Finn", "petfinn.com", null, null, null),
      b("Native Pet", "nativepet.com", null, null, null),
      b("PetHonesty", "pethonesty.com", null, null, null),
      b("Shameless Pets", "shamelesspets.com", null, null, null),
      b("The Innocent Pet", "theinnocentpet.co.uk", null, null, null),
    ],
  },
  {
    id: "fitness",
    label: "Health & Fitness",
    brands: [
      b("1st Phorm", "1stphorm.com", null, null, null),
      b("Alani Nu", "alaninu.com", null, null, null),
      b("Bells of Steel", "bellsofsteel.com", null, null, null),
      b("Bloom Nutrition", "bloomnu.com", null, null, null),
      b("BOSU", "bosu.com", null, null, null),
      b("BPN", "bareperformancenutrition.com", null, null, null),
      b("Cellucor", "cellucor.com", null, null, null),
      b("Fringe Sport", "fringesport.com", null, null, null),
      b("Ghost Lifestyle", "ghostlifestyle.com", null, null, null),
      b("Gorilla Mind", "gorillamind.com", null, null, null),
      b("Hyperice", "hyperice.com", null, null, null),
      b("Jacked Factory", "jackedfactory.com", null, null, null),
      b("Momentous", "livemomentous.com", null, null, null),
      b("Optimum Nutrition", "optimumnutrition.com", null, null, null),
      b("Peloton", "apparel.onepeloton.com", null, null, null),
      b("PEScience", "pescience.com", null, null, null),
      b("Power Systems", "power-systems.com", null, null, null),
      b("PRx Performance", "prxperformance.com", null, null, null),
      b("Redcon1", "redcon1.com", null, null, null),
      b("Rep Fitness", "repfitness.com", null, null, null),
      b("Swolverine", "swolverine.com", null, null, null),
      b("Therabody", "therabody.com", null, null, null),
      b("Tonal", "tonal.com", null, null, null),
      b("Transparent Labs", "transparentlabs.com", null, null, null),
      b("TRX", "trxtraining.com", null, null, null),
      b("XWERKS", "xwerks.com", null, null, null),
      b("Adanola", "adanola.com", "UK", "activewear", "Manchester-based women's activewear and athleisure label."),
      b("Again Faster", "againfaster.com", "UK", "functional fitness equipment", "UK arm of CrossFit-focused equipment retailer selling barbells, plates and rigs."),
      b("Awesome Supplements", "awesomesupplements.co.uk", "UK", "supplements", "UK evidence-based supplement brand co-founded by Ben Coomber producing protein, creatine and pre-workouts."),
      b("AYBL", "aybl.com", "UK", "gym apparel", "UK fitness apparel brand offering leggings, shorts and training tops."),
      b("Battle Bites", "battlebites.co.uk", "UK", "protein snacks", "UK protein bar and snack brand."),
      b("Bio-Synergy", "bio-synergy.uk", "UK", "supplements", "Long-running UK sports nutrition brand selling protein, fat burners and vitamins."),
      b("Bulldog Gear", "bulldoggear.com", "UK", "functional fitness equipment", "British functional training equipment brand - racks, barbells, accessories."),
      b("Grenade", "grenade.com", "UK", "sports nutrition", "UK performance nutrition brand known for Carb Killa bars and pre-workouts."),
      b("Gym+Coffee", "gympluscoffee.com", "UK", "activewear", "Irish/UK athleisure brand with hoodies and performance gear serving the UK market."),
      b("Innermost", "innermostglobal.com", "UK", "supplements", "UK wellness brand selling protein powders, collagen, vitamins and functional supplements targeted at outcomes like sleep and energy."),
      b("JTX Fitness", "jtxfitness.com", "UK", "cardio equipment", "UK direct-to-consumer cardio equipment brand (treadmills, bikes, rowers)."),
      b("Kettlebell Kings UK", "kettlebellkings.co.uk", "UK", "kettlebells / strength", "UK storefront for specialist kettlebell equipment retailer."),
      b("Mirafit", "mirafit.co.uk", "UK", "home gym equipment", "UK home gym and strength equipment retailer - racks, barbells, benches."),
      b("Momentous (UK)", "gains-in-bulk.myshopify.com", "UK", "bulk supplements", "UK bulk supplement and powder retailer."),
      b("Pursue Fitness", "pursuefitness.com", "UK", "gym apparel", "Manchester-based men's and women's gym wear brand."),
      b("Shreddy", "shreddy.com", "UK", "activewear / fitness app", "Grace Beverley-founded women's fitness apparel and programme brand."),
      b("Strength Shop", "strengthshop.co.uk", "UK", "powerlifting equipment", "UK powerlifting equipment and apparel retailer."),
      b("Tala", "wearetala.com", "UK", "activewear", "Sustainable women's activewear brand founded by Grace Beverley; leggings, sports bras and loungewear."),
      b("TRIBE", "wearetribe.co", "UK", "sports nutrition", "UK natural energy and protein brand selling bars, shakes and hydration to endurance athletes."),
      b("Vitl", "vitl.com", "UK", "personalised vitamins", "UK personalised vitamin subscription service offering bespoke daily packs based on consultation."),
      b("Vivo Life", "vivolife.com", "UK", "plant-based supplements", "UK plant-based vegan supplement brand producing protein, greens and immunity products."),
      b("Wolverson Fitness", "wolverson-fitness.co.uk", "UK", "strength equipment", "UK strength and conditioning equipment manufacturer."),
      b("HydroJug", "hydrojug.com", null, null, null),
      b("More Muscle", "moremuscle.com", null, null, null),
      b("Bala", "shopbala.com", null, null, null),
      b("Needed", "thisisneeded.com", null, null, null),
      b("Cymbiotika", "cymbiotika.com", null, null, null),
      b("Heights", "yourheights.com", null, null, null),
      b("Kion", "getkion.com", null, null, null),
      b("Wild Nutrition", "wildnutrition.com", null, null, null),
      b("Together Health", "togetherhealth.co.uk", null, null, null),
      b("Grass & Co.", "grassandco.com", null, null, null),
    ],
  },
  {
    id: "jewellery",
    label: "Jewellery & Accessories",
    brands: [
      b("Argent", "argentwork.com", null, null, null),
      b("Aurate", "auratenewyork.com", null, null, null),
      b("BaubleBar", "baublebar.com", null, null, null),
      b("Brandon Blackwood", "brandonblackwood.com", null, null, null),
      b("Brother Vellies", "brothervellies.com", null, null, null),
      b("Cult Gaia", "cultgaia.com", null, null, null),
      b("Cuyana", "cuyana.com", null, null, null),
      b("Everlane", "everlane.com", null, null, null),
      b("For Days", "fordays.com", null, null, null),
      b("Girlfriend Collective", "girlfriend.com", null, null, null),
      b("Gorjana", "gorjana.com", null, null, null),
      b("Jenny Bird", "jenny-bird.com", null, null, null),
      b("JW Pei", "jwpei.com", null, null, null),
      b("Loeffler Randall", "loefflerrandall.com", null, null, null),
      b("M.M.LaFleur", "mmlafleur.com", null, null, null),
      b("Mansur Gavriel", "mansurgavriel.com", null, null, null),
      b("Ministry of Supply", "ministryofsupply.com", null, null, null),
      b("Missoma", "missoma.com", null, null, null),
      b("Nanushka", "nanushka.com", null, null, null),
      b("Nisolo", "nisolo.com", null, null, null),
      b("Pangaia", "thepangaia.com", null, null, null),
      b("Ring Concierge", "ringconcierge.com", null, null, null),
      b("SOKO", "shopsoko.com", null, null, null),
      b("Stone and Strand", "stoneandstrand.com", null, null, null),
      b("The Row", "therow.com", null, null, null),
      b("Uncommon James", "uncommonjames.com", null, null, null),
      b("Universal Standard", "universalstandard.com", null, null, null),
      b("Vitaly", "vitalydesign.com", null, null, null),
      b("Abbott Lyon", "abbottlyon.com", "UK", "personalised jewellery", "UK personalised jewellery and watches brand."),
      b("Alighieri", "alighieri.com", "UK", "fine jewellery", "London jewellery brand by Rosh Mahtani inspired by Dante, hand-cast in the UK."),
      b("Anya Hindmarch", "anyahindmarch.com", "UK", "luxury bags", "British luxury leather goods and handbags brand."),
      b("Aspinal of London", "aspinaloflondon.com", "UK", "luxury leather goods", "British luxury handbag and leather accessories brand."),
      b("Astrid & Miyu", "astridandmiyu.com", "UK", "demi-fine jewellery", "London contemporary demi-fine jewellery brand known for ear stacks and piercing services."),
      b("Cambridge Satchel", "cambridgesatchel.com", "UK", "leather bags", "British leather satchel and bag maker founded by Julie Deane."),
      b("Carl Friedrik", "carlfriedrik.com", "UK", "leather goods", "London premium leather luggage, bags and wallets brand."),
      b("CRAFTD London", "craftdlondon.com", "UK", "men's jewellery", "London men's premium jewellery brand known for chains and rings."),
      b("Daisy London", "daisyjewellery.com", "UK", "fashion jewellery", "London jewellery brand founded 2009 known for classic, everyday pieces."),
      b("Edge of Ember", "edgeofember.com", "UK", "ethical fine jewellery", "London ethical jewellery label using recycled materials and lab-grown diamonds."),
      b("Farer", "farer.com", "UK", "watches", "London-designed, Swiss-made independent watch brand."),
      b("Hannah Martin", "hannahmartinlondon.com", "UK", "fine jewellery", "London fine jewellery designer known for sculptural unisex pieces."),
      b("Larsson & Jennings", "larssonandjennings.com", "UK", "watches", "London minimalist DTC watch and jewellery brand."),
      b("Lily & Roo", "lilyandroo.com", "UK", "fine jewellery", "British solid gold and silver jewellery brand."),
      b("Maxwell-Scott", "maxwellscottbags.com", "UK", "leather bags", "British Italian-crafted leather handbags and luggage brand."),
      b("Otiumberg", "otiumberg.com", "UK", "demi-fine jewellery", "London demi-fine jewellery brand by sisters Christie and Rosanna Wollenberg."),
      b("Pomellato-alternative: Roxanne First", "roxannefirst.com", "UK", "fine jewellery", "London colourful fine jewellery brand by Roxanne Rajcoomar-Hadden."),
      b("Rachel Jackson London", "racheljacksonlondon.com", "UK", "demi-fine jewellery", "London jewellery brand worn by Rita Ora, Ellie Goulding and Kylie Jenner."),
      b("Shrimps", "shrimps.com", "UK", "bags & accessories", "London label known for faux-fur bags, beaded accessories and playful ready-to-wear."),
      b("Stow London", "stowlondon.co.uk", "UK", "luxury leather goods", "London luxury personalised leather travel accessories brand."),
      b("Strathberry", "strathberry.com", "UK", "luxury bags", "Edinburgh luxury handbag brand, worn by the Princess of Wales."),
      b("Tatty Devine", "tattydevine.com", "UK", "statement jewellery", "London statement acrylic jewellery brand, handmade in the UK."),
      b("Tilly Sveaas", "tillysveaas.co.uk", "UK", "demi-fine jewellery", "London demi-fine jewellery brand famed for T-bar necklaces."),
      b("Troubadour Goods", "troubadourgoods.com", "UK", "bags & accessories", "London premium work bag and accessories brand."),
      b("Vashi", "vashi.com", "UK", "fine jewellery", "London bespoke diamond and fine jewellery brand."),
      b("Wanderlust Life", "wanderlustlife.co.uk", "UK", "handmade jewellery", "Devon-based independent B Corp handmade jewellery studio."),
      b("Pura Vida", "puravidabracelets.com", null, null, null),
      b("Dagne Dover", "dagnedover.com", null, null, null),
      b("Baboon to the Moon", "baboontothemoon.com", null, null, null),
      b("BÉIS", "beistravel.com", null, null, null),
      b("KINN", "kinnstudio.com", null, null, null),
      b("Lo & Sons", "loandsons.com", null, null, null),
      b("Oma The Label", "omathelabel.com", null, null, null),
    ],
  },
  {
    id: "mobility",
    label: "Automotive & Mobility",
    brands: [
      b("Ariel Rider", "arielrider.com", null, null, null),
      b("Aventon", "aventon.com", null, null, null),
      b("Backfire", "backfireboards.com", null, null, null),
      b("Evil Bikes", "evil-bikes.com", null, null, null),
      b("Evolve Skateboards", "evolveskateboardsusa.com", null, null, null),
      b("Exway", "exwayboard.com", null, null, null),
      b("Hovsco", "hovsco.com", null, null, null),
      b("Islabikes", "islabikes.com", null, null, null),
      b("Juiced Bikes", "juicedbikes.com", null, null, null),
      b("Lectric", "lectricebikes.com", null, null, null),
      b("Meepo", "meepoboard.com", null, null, null),
      b("Ownboard", "ownboard.net", null, null, null),
      b("Pivot", "pivotcycles.com", null, null, null),
      b("Priority Bicycles", "prioritybicycles.com", null, null, null),
      b("Pure Cycles", "purecycles.com", null, null, null),
      b("Retrospec", "retrospec.com", null, null, null),
      b("Santa Cruz", "santacruzbicycles.com", null, null, null),
      b("Sole Bicycles", "solebicycles.com", null, null, null),
      b("State Bicycle", "statebicycle.com", null, null, null),
      b("Super73", "super73.com", null, null, null),
      b("WowGo", "wowgoboard.com", null, null, null),
      b("Auto Finesse", "autofinesse.com", "UK", "car detailing", "Essex-based UK car detailing products brand."),
      b("Batribike", "batribike.com", "UK", "e-bikes", "Lincolnshire-based UK e-bike brand with folding and step-through models."),
      b("Bicycle Chain Reaction / Pashley", "pashley.co.uk", "UK", "heritage bikes", "Stratford-upon-Avon-based heritage UK bicycle manufacturer."),
      b("Bowman Cycles", "bowman-cycles.com", "UK", "road / gravel bikes", "UK independent road and gravel frameset brand."),
      b("Cyrusher UK", "cyrusher.co.uk", "UK", "e-bikes", "UK fat-tyre and off-road e-bike brand."),
      b("Electroheads", "electroheads.com", "UK", "e-bike / e-scooter retailer", "UK multi-brand e-bike and e-scooter retailer launched in 2020."),
      b("Eskuta", "eskuta.com", "UK", "e-bikes / e-scooters", "UK electric moped and commercial e-bike manufacturer."),
      b("Estarli", "estarli.co.uk", "UK", "e-bikes", "Hertfordshire-based folding, full-size and cargo e-bike brand."),
      b("Fabric Bikes UK", "fabric.cc", "UK", "cycling accessories", "UK cycling saddles, bottles, tools and accessories brand."),
      b("Fiido UK", "fiido.com", "UK", "e-bikes", "UK storefront for global Fiido folding and commuter e-bikes."),
      b("Freego E-Bikes", "freego.eu", "UK", "e-bikes", "UK e-bike brand with hybrid, folding and step-through models."),
      b("Genesis Bikes", "genesisbikes.co.uk", "UK", "gravel / road bikes", "British adventure, gravel and road bike brand."),
      b("Hiplok", "hiplok.com", "UK", "bike locks", "Warwickshire-based wearable bike lock brand."),
      b("Knog UK", "knog.com.au", "EU", "bike lights", "Australian cycling lights brand with UK retail presence."),
      b("Mycle", "mycle.co.uk", "UK", "e-bikes", "UK affordable e-bike brand with folding, step-through and cargo models."),
      b("Orange Bikes", "orangebikes.co.uk", "UK", "mountain bikes", "Halifax-based hand-built UK mountain bike brand."),
      b("Pace Cycles", "pace-cycles.myshopify.com", "UK", "mountain bikes", "Yorkshire-based UK mountain bike and component brand."),
      b("Pure Electric", "pureelectric.com", "UK", "e-scooters", "UK specialist e-scooter and e-bike retailer with national footprint."),
      b("Raleigh UK", "raleigh.co.uk", "UK", "bikes / e-bikes", "Heritage UK bicycle brand offering e-bikes, hybrids and kids bikes."),
      b("Restrap", "restrap.co.uk", "UK", "bikepacking gear", "UK bikepacking bag brand (UK storefront)."),
      b("Swytch Bike", "swytchbike.com", "UK", "e-bike conversion", "London-based e-bike conversion kit brand."),
      b("Temple Cycles", "templecycles.co.uk", "UK", "city / commuter bikes", "Bristol-based heritage-style city bike brand."),
      b("Tern (UK)", "store.ternbicycles.com", "US", "folding / cargo bikes", "Folding and cargo bike brand with strong UK distribution."),
      b("Unagi UK", "shop.unagiscooters.com", "US", "e-scooters", "Premium e-scooter brand serving UK shoppers."),
      b("Whyte Bikes", "whytebikes.com", "UK", "mountain bikes", "British mountain bike brand with trail, enduro and e-MTB models."),
      b("Wisper Bikes", "wisperbikes.myshopify.com", "UK", "e-bikes", "Kent-based long-established UK e-bike manufacturer."),
      b("sixthreezero", "sixthreezero.com", null, null, null),
      b("Rad Power Bikes", "radpowerbikes.com", null, null, null),
      b("ENGWE", "engwe.com", null, null, null),
      b("Chemical Guys", "chemicalguys.com", null, null, null),
      b("Adam's Polishes", "adamspolishes.com", null, null, null),
      b("Knog", "knog.com", null, null, null),
    ],
  },
  {
    id: "travel-luggage",
    label: "Travel & Luggage",
    brands: [
      b("Antler", "antler.com", null, null, null),
      b("Horizn Studios", "horizn-studios.com", null, null, null),
      b("Db", "dbjourney.com", null, null, null),
      b("WANDRD", "wandrd.com", null, null, null),
      b("Tropicfeel", "tropicfeel.com", null, null, null),
      b("Stubble & Co", "stubbleandco.com", null, null, null),
      b("Arlo Skye", "arloskye.com", null, null, null),
    ],
  },
  {
    id: "fragrance",
    label: "Fragrance",
    brands: [
      b("Noteology", "noteology.com", null, null, null),
      b("Snif", "snif.co", null, null, null),
      b("DedCool", "dedcool.com", null, null, null),
      b("Ellis Brooklyn", "ellisbrooklyn.com", null, null, null),
      b("Commodity", "commodityfragrances.com", null, null, null),
      b("Boy Smells", "boysmells.com", null, null, null),
      b("Floral Street", "floralstreet.com", null, null, null),
      b("Sana Jardin", "sanajardin.com", null, null, null),
      b("Henry Rose", "henryrose.com", null, null, null),
    ],
  },
  {
    id: "eyewear",
    label: "Eyewear",
    brands: [
      b("DIFF Eyewear", "diffeyewear.com", null, null, null),
      b("goodr", "goodr.com", null, null, null),
      b("Finlay & Co", "finlayandco.com", null, null, null),
      b("Caddis", "caddislife.com", null, null, null),
      b("Banton Frameworks", "bantonframeworks.co.uk", null, null, null),
      b("ROKA", "roka.com", null, null, null),
      b("Cubitts", "cubitts.com", null, null, null),
      b("Sunski", "sunski.com", null, null, null),
      b("Knockaround", "knockaround.com", null, null, null),
      b("Vallon", "vallon.com", null, null, null),
    ],
  },
  {
    id: "watches",
    label: "Watches",
    brands: [
      b("UNDONE", "undone.com", null, null, null),
      b("Nordgreen", "nordgreen.com", null, null, null),
      b("TRIWA", "triwa.com", null, null, null),
      b("Shore Projects", "shoreprojects.com", null, null, null),
      b("BREW", "brewwatches.com", null, null, null),
      b("Autodromo", "autodromo.com", null, null, null),
    ],
  },
  {
    id: "stationery-gifts",
    label: "Stationery & Gifts",
    brands: [
      b("Mossery", "mossery.co", null, null, null),
      b("Notebook Therapy", "notebooktherapy.com", null, null, null),
      b("Katie Leamon", "katieleamon.com", null, null, null),
      b("Ohh Deer", "ohhdeer.com", null, null, null),
      b("Galen Leather", "galenleather.com", null, null, null),
      b("Cloth & Paper", "clothandpaper.com", null, null, null),
      b("Ugmonk", "ugmonk.com", null, null, null),
      b("Appointed", "appointed.co", null, null, null),
      b("Baronfig", "baronfig.com", null, null, null),
    ],
  },
];

// Flat list of all brands, useful for generateStaticParams
export const ALL_BRANDS: (Brand & { vertical: Vertical })[] = VERTICALS.flatMap((v) =>
  v.brands.map((b) => ({ ...b, vertical: v }))
);

// Notional total product count for marketing copy (homepage, pricing).
// Based on ALL_BRANDS.length * notional average. Real per-brand counts are
// fetched dynamically from Supabase at render time via brandStats.ts.
export const TOTAL_PRODUCTS = ALL_BRANDS.length * 2500;

// Flat list of brand names for marquees / logo strips
export const BRAND_NAMES = ALL_BRANDS.map((b) => b.name);

// Logo-style brand wordmarks with unique typography for the homepage marquee
export const BRAND_WORDMARKS: { name: string; style: string }[] = [
  // Fashion
  { name: "GYMSHARK", style: "font-bold tracking-wider" },
  { name: "FASHION NOVA", style: "font-black tracking-wide text-[11px]" },
  { name: "SKIMS", style: "font-bold tracking-[0.3em]" },
  { name: "alo", style: "font-light tracking-[0.4em] uppercase" },
  { name: "KITH", style: "font-black tracking-[0.2em]" },
  { name: "FIGS", style: "font-black tracking-[0.3em]" },
  { name: "allbirds", style: "font-medium lowercase" },
  { name: "Vuori", style: "font-medium" },
  { name: "Rhone", style: "font-semibold tracking-wide" },
  { name: "TRUE CLASSIC", style: "font-bold tracking-wider text-[11px]" },
  { name: "REPRESENT", style: "font-black tracking-[0.15em]" },
  { name: "MVMT", style: "font-bold tracking-[0.3em]" },
  { name: "AWAY", style: "font-bold tracking-[0.25em]" },
  { name: "Chubbies", style: "font-bold" },
  { name: "SAVAGE X", style: "font-black tracking-wider text-[11px]" },
  { name: "OBEY", style: "font-black tracking-[0.35em]" },
  { name: "the hundreds", style: "font-bold lowercase tracking-wide" },
  // Beauty
  { name: "FENTY BEAUTY", style: "font-bold tracking-widest text-[11px]" },
  { name: "rare beauty", style: "font-medium lowercase italic" },
  { name: "KYLIE", style: "font-bold tracking-[0.35em]" },
  { name: "Glossier", style: "font-medium italic" },
  { name: "ColourPop", style: "font-bold" },
  { name: "HISMILE", style: "font-black tracking-wider text-[11px]" },
  { name: "OLAPLEX", style: "font-bold tracking-[0.2em]" },
  { name: "Dr. Squatch", style: "font-bold" },
  { name: "ritual", style: "font-medium lowercase" },
  { name: "AG1", style: "font-black tracking-[0.2em]" },
  { name: "cocokind", style: "font-light lowercase tracking-wide" },
  { name: "PIXI", style: "font-bold tracking-[0.4em]" },
  { name: "native", style: "font-semibold lowercase" },
  { name: "KOPARI", style: "font-medium tracking-[0.3em]" },
  { name: "prose", style: "font-light lowercase italic tracking-wider" },
  { name: "hims", style: "font-bold lowercase" },
  // Home
  { name: "RUGGABLE", style: "font-medium tracking-[0.2em]" },
  { name: "casper", style: "font-bold lowercase" },
  { name: "Stanley 1913", style: "font-semibold" },
  { name: "BROOKLINEN", style: "font-medium tracking-wide" },
  { name: "YETI", style: "font-black tracking-[0.25em]" },
  { name: "Ooni", style: "font-bold" },
  { name: "Peak Design", style: "font-semibold" },
  { name: "Keychron", style: "font-medium" },
  { name: "PURPLE", style: "font-black tracking-[0.15em]" },
  { name: "article", style: "font-light lowercase tracking-[0.3em]" },
  { name: "TRAEGER", style: "font-bold tracking-wider" },
  { name: "Snow Peak", style: "font-medium italic" },
  { name: "TIMBUK2", style: "font-black tracking-wide text-[11px]" },
  // Food
  { name: "LIQUID DEATH", style: "font-black tracking-wider text-[11px]" },
  { name: "huel", style: "font-bold lowercase" },
  { name: "Magic Spoon", style: "font-bold" },
  { name: "Owala", style: "font-bold" },
  { name: "Fellow", style: "font-medium" },
  { name: "HexClad", style: "font-semibold" },
  { name: "olipop", style: "font-bold lowercase tracking-wide" },
  { name: "GRAZA", style: "font-black tracking-[0.3em]" },
  { name: "ghia", style: "font-light lowercase italic" },
  { name: "Blue Bottle", style: "font-medium" },
  // Electronics
  { name: "NOMAD", style: "font-bold tracking-[0.3em]" },
  { name: "RIDGE", style: "font-black tracking-[0.25em]" },
  { name: "secretlab", style: "font-bold lowercase" },
  { name: "Jackery", style: "font-semibold" },
  { name: "NANOLEAF", style: "font-medium tracking-[0.15em]" },
  { name: "RAZER", style: "font-black tracking-[0.2em]" },
  { name: "Raspberry Pi", style: "font-medium" },
  { name: "Bombas", style: "font-bold" },
  { name: "Rothy's", style: "font-medium italic" },
  { name: "MOMENT", style: "font-medium tracking-[0.2em]" },
  { name: "CORSAIR", style: "font-bold tracking-[0.25em]" },
  { name: "SENNHEISER", style: "font-light tracking-[0.4em] uppercase text-[10px]" },
  { name: "dbrand", style: "font-black lowercase" },
  { name: "nothing", style: "font-light lowercase tracking-[0.2em]" },
  { name: "Bambu Lab", style: "font-semibold" },
  { name: "ANKER", style: "font-bold tracking-[0.2em]" },
  { name: "teenage engineering", style: "font-light lowercase tracking-wider text-[10px]" },
  { name: "Oura", style: "font-medium italic" },
  { name: "Insta360", style: "font-semibold" },
  { name: "remarkable", style: "font-light lowercase tracking-[0.3em]" },
  // Sports & Outdoors
  { name: "HOKA", style: "font-black tracking-[0.2em]" },
  { name: "On", style: "font-bold tracking-[0.4em] uppercase" },
  { name: "SALOMON", style: "font-bold tracking-[0.25em]" },
  { name: "ARC'TERYX", style: "font-medium tracking-[0.2em]" },
  { name: "patagonia", style: "font-bold lowercase" },
  { name: "THE NORTH FACE", style: "font-black tracking-wider text-[10px]" },
  { name: "Osprey", style: "font-semibold italic" },
  { name: "SITKA", style: "font-black tracking-[0.3em]" },
  { name: "Filson", style: "font-bold" },
  // Kids & Baby
  { name: "Lovevery", style: "font-medium" },
  { name: "NUGGET", style: "font-black tracking-[0.25em]" },
  { name: "KiwiCo", style: "font-bold" },
  { name: "Kyte Baby", style: "font-light italic tracking-wide" },
  { name: "UPPAbaby", style: "font-semibold" },
  // Pets
  { name: "BARKBOX", style: "font-black tracking-wider text-[11px]" },
  { name: "wild one", style: "font-medium lowercase tracking-[0.2em]" },
  { name: "RUFFWEAR", style: "font-bold tracking-[0.2em]" },
  { name: "Litter-Robot", style: "font-semibold" },
  // Health & Fitness
  { name: "THERABODY", style: "font-bold tracking-[0.25em]" },
  { name: "ROGUE", style: "font-black tracking-[0.3em]" },
  { name: "GHOST", style: "font-black tracking-[0.35em]" },
  { name: "alani nu", style: "font-medium lowercase" },
  { name: "MYPROTEIN", style: "font-bold tracking-wide" },
  // Jewellery & Accessories
  { name: "mejuri", style: "font-light lowercase tracking-[0.3em]" },
  { name: "MISSOMA", style: "font-medium tracking-[0.2em]" },
  { name: "KENDRA SCOTT", style: "font-bold tracking-wider text-[10px]" },
  { name: "Brilliant Earth", style: "font-medium italic" },
  { name: "Polene", style: "font-light tracking-[0.25em]" },
  { name: "TELFAR", style: "font-black tracking-[0.3em]" },
  // Automotive & Mobility
  { name: "SUPER73", style: "font-black tracking-[0.2em]" },
  { name: "RadPower", style: "font-bold" },
  { name: "Canyon", style: "font-semibold" },
  { name: "SANTA CRUZ", style: "font-black tracking-wider text-[10px]" },
  { name: "SPECIALIZED", style: "font-medium tracking-[0.15em]" },
];
